import type { Kpi } from "./config";

export type FieldType = "text" | "number" | "date" | "select";

export interface Field {
  key: string;
  label: string;
  type: FieldType;
  options?: string[];
  required?: boolean;
  placeholder?: string;
}

export interface Column {
  key: string;
  label: string;
  align?: "left" | "right";
  kind?: "text" | "status" | "money";
}

export type Row = Record<string, string | number>;

export interface Workspace {
  id: string;
  icon: string;
  title: string;
  subtitle: string;
  kpis: Kpi[];
  columns: Column[];
  rows: Row[];
  fields: Field[];
  createLabel: string;
  /** key of the column that carries a status value */
  statusKey?: string;
  /** monthly series for the trend chart */
  series?: { name: string; value: number }[];
  seriesLabel?: string;
}

const months = ["Mar", "Apr", "May", "Jun", "Jul", "Aug"];
const series = (...v: number[]) => months.map((name, i) => ({ name, value: v[i] ?? 0 }));

export const WORKSPACES: Record<string, Workspace> = {
  tenants: {
    id: "tenants",
    icon: "Building2",
    title: "Platform & Tenant Administration",
    subtitle: "Onboard and configure clinic tenants and branches",
    kpis: [
      { label: "Tenants active", value: "38", trend: "+3 this month", trendTone: "up" },
      { label: "Branches", value: "112", trend: "+7", trendTone: "up" },
      { label: "Trials running", value: "5", trend: "2 expiring", trendTone: "flat" },
      { label: "Suspended", value: "1", trend: "payment failed", trendTone: "down" },
    ],
    seriesLabel: "Tenants onboarded",
    series: series(24, 27, 30, 33, 35, 38),
    columns: [
      { key: "name", label: "Tenant" },
      { key: "code", label: "Tenant ID" },
      { key: "branches", label: "Branches", align: "right" },
      { key: "plan", label: "Plan" },
      { key: "status", label: "Status", kind: "status" },
      { key: "since", label: "Onboarded" },
    ],
    statusKey: "status",
    rows: [
      { name: "Paws & Claws", code: "TEN-1001", branches: 6, plan: "Enterprise", status: "Active", since: "2024-03-11" },
      { name: "PetWell Group", code: "TEN-1002", branches: 4, plan: "Growth", status: "Active", since: "2024-07-02" },
      { name: "Happy Tails", code: "TEN-1003", branches: 2, plan: "Starter", status: "Trial", since: "2026-07-28" },
      { name: "VetCare Nagpur", code: "TEN-1004", branches: 1, plan: "Starter", status: "Suspended", since: "2025-01-19" },
      { name: "Animalia Clinics", code: "TEN-1005", branches: 9, plan: "Enterprise", status: "Active", since: "2023-11-05" },
    ],
    createLabel: "Onboard Tenant",
    fields: [
      { key: "name", label: "Tenant name", type: "text", required: true, placeholder: "Clinic group name" },
      { key: "code", label: "Tenant ID", type: "text", required: true, placeholder: "TEN-1006" },
      { key: "branches", label: "Branches", type: "number", required: true },
      { key: "plan", label: "Plan", type: "select", options: ["Starter", "Growth", "Enterprise"], required: true },
      { key: "status", label: "Status", type: "select", options: ["Active", "Trial", "Suspended"], required: true },
      { key: "since", label: "Onboarded", type: "date", required: true },
    ],
  },

  subscriptions: {
    id: "subscriptions",
    icon: "CreditCard",
    title: "Subscription & SaaS Administration",
    subtitle: "Plans, entitlements and billing per tenant",
    kpis: [
      { label: "MRR", value: "₹18.4L", trend: "+6.2%", trendTone: "up" },
      { label: "Renewals this week", value: "6", trend: "2 overdue", trendTone: "down" },
      { label: "Churn (90d)", value: "1.8%", trend: "-0.4%", trendTone: "up" },
      { label: "Avg. seats/tenant", value: "27", trend: "+2", trendTone: "up" },
    ],
    seriesLabel: "MRR (₹ lakh)",
    series: series(13.1, 14.4, 15.2, 16.6, 17.3, 18.4),
    columns: [
      { key: "tenant", label: "Tenant" },
      { key: "plan", label: "Plan" },
      { key: "seats", label: "Seats", align: "right" },
      { key: "amount", label: "Monthly", align: "right", kind: "money" },
      { key: "renewal", label: "Renews" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { tenant: "Paws & Claws", plan: "Enterprise", seats: 64, amount: 74000, renewal: "2026-08-20", status: "Active" },
      { tenant: "PetWell Group", plan: "Growth", seats: 32, amount: 38000, renewal: "2026-08-18", status: "Due" },
      { tenant: "Happy Tails", plan: "Starter", seats: 8, amount: 9000, renewal: "2026-08-27", status: "Trial" },
      { tenant: "VetCare Nagpur", plan: "Starter", seats: 6, amount: 9000, renewal: "2026-08-09", status: "Overdue" },
      { tenant: "Animalia Clinics", plan: "Enterprise", seats: 91, amount: 108000, renewal: "2026-09-01", status: "Active" },
    ],
    createLabel: "New Subscription",
    fields: [
      { key: "tenant", label: "Tenant", type: "text", required: true },
      { key: "plan", label: "Plan", type: "select", options: ["Starter", "Growth", "Enterprise"], required: true },
      { key: "seats", label: "Seats", type: "number", required: true },
      { key: "amount", label: "Monthly amount", type: "number", required: true },
      { key: "renewal", label: "Renewal date", type: "date", required: true },
      { key: "status", label: "Status", type: "select", options: ["Active", "Due", "Trial", "Overdue"], required: true },
    ],
  },

  "identity-global": {
    id: "identity-global",
    icon: "ShieldCheck",
    title: "Identity & Access (Global)",
    subtitle: "Global roles, permission templates and security policy",
    kpis: [
      { label: "Admins across tenants", value: "0", trend: "0", trendTone: "flat" },
      { label: "Permission templates", value: "0", trend: "standard", trendTone: "flat" },
      { label: "MFA enforced", value: "0%", trend: "0%", trendTone: "flat" },
      { label: "Dormant accounts", value: "0", trend: "none", trendTone: "flat" },
    ],
    columns: [
      { key: "user", label: "User" },
      { key: "tenant", label: "Tenant" },
      { key: "role", label: "Role" },
      { key: "mfa", label: "MFA" },
      { key: "lastSeen", label: "Last active" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "Invite Admin",
    fields: [
      { key: "user", label: "Full name", type: "text", required: true },
      { key: "tenant", label: "Tenant", type: "text", required: true },
      { key: "role", label: "Role", type: "select", options: ["Admin", "Accountant", "Receptionist", "Platform Admin"], required: true },
      { key: "mfa", label: "MFA", type: "select", options: ["Enabled", "Disabled"], required: true },
      { key: "lastSeen", label: "Last active", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["Active", "Review", "Dormant"], required: true },
    ],
  },

  "integrations-global": {
    id: "integrations-global",
    icon: "Plug",
    title: "Integration Hub & Settings (Global)",
    subtitle: "WhatsApp, SMS, payment gateway and GST providers",
    kpis: [
      { label: "Integrations connected", value: "0", trend: "none", trendTone: "flat" },
      { label: "Failing", value: "0", trend: "none", trendTone: "flat" },
      { label: "API calls (24h)", value: "0", trend: "0%", trendTone: "flat" },
      { label: "Avg. latency", value: "0ms", trend: "normal", trendTone: "flat" },
    ],
    columns: [
      { key: "provider", label: "Provider" },
      { key: "type", label: "Type" },
      { key: "tenants", label: "Tenants", align: "right" },
      { key: "calls", label: "Calls (24h)", align: "right" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "Connect Provider",
    fields: [
      { key: "provider", label: "Provider", type: "text", required: true },
      { key: "type", label: "Type", type: "select", options: ["Messaging", "Payments", "Compliance", "Email"], required: true },
      { key: "tenants", label: "Tenants enabled", type: "number" },
      { key: "calls", label: "Calls (24h)", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["Connected", "Failing", "Disabled"], required: true },
    ],
  },

  "reports-platform": {
    id: "reports-platform",
    icon: "BarChart3",
    title: "Reports & Analytics (Platform-wide)",
    subtitle: "Cross-tenant usage, revenue and health metrics",
    kpis: [
      { label: "Tenants flagged", value: "4", trend: "+1", trendTone: "down" },
      { label: "Reports scheduled", value: "14", trend: "weekly", trendTone: "flat" },
      { label: "Avg. usage score", value: "72", trend: "+3", trendTone: "up" },
      { label: "Revenue/tenant", value: "₹48.4k", trend: "+5%", trendTone: "up" },
    ],
    seriesLabel: "Platform revenue (₹ lakh)",
    series: series(13.1, 14.4, 15.2, 16.6, 17.3, 18.4),
    columns: [
      { key: "report", label: "Report" },
      { key: "scope", label: "Scope" },
      { key: "frequency", label: "Frequency" },
      { key: "owner", label: "Owner" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { report: "Tenant health scorecard", scope: "All tenants", frequency: "Weekly", owner: "Platform Ops", status: "Scheduled" },
      { report: "Revenue by plan", scope: "All tenants", frequency: "Monthly", owner: "Finance", status: "Scheduled" },
      { report: "Feature adoption", scope: "Enterprise", frequency: "Monthly", owner: "Product", status: "Draft" },
      { report: "Churn risk list", scope: "Starter", frequency: "Weekly", owner: "Success", status: "Scheduled" },
    ],
    createLabel: "New Report",
    fields: [
      { key: "report", label: "Report name", type: "text", required: true },
      { key: "scope", label: "Scope", type: "text", required: true },
      { key: "frequency", label: "Frequency", type: "select", options: ["Daily", "Weekly", "Monthly"], required: true },
      { key: "owner", label: "Owner", type: "text" },
      { key: "status", label: "Status", type: "select", options: ["Scheduled", "Draft", "Paused"], required: true },
    ],
  },

  audit: {
    id: "audit",
    icon: "Activity",
    title: "Audit & System Health",
    subtitle: "Audit trail, backup status and incident log",
    kpis: [
      { label: "Failed jobs / alerts", value: "3", trend: "1 critical", trendTone: "down" },
      { label: "Uptime (30d)", value: "99.98%", trend: "SLA met", trendTone: "up" },
      { label: "Last backup", value: "02:00", trend: "successful", trendTone: "up" },
      { label: "Audit events (24h)", value: "8,412", trend: "+6%", trendTone: "flat" },
    ],
    columns: [
      { key: "time", label: "Time" },
      { key: "event", label: "Event" },
      { key: "actor", label: "Actor" },
      { key: "tenant", label: "Tenant" },
      { key: "status", label: "Severity", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { time: "2026-08-15 11:42", event: "Nightly billing job failed", actor: "system", tenant: "VetCare Nagpur", status: "Critical" },
      { time: "2026-08-15 10:18", event: "Permission template updated", actor: "Ishaan Verma", tenant: "Paws & Claws", status: "Info" },
      { time: "2026-08-15 09:03", event: "SMS provider timeout", actor: "system", tenant: "All", status: "Warning" },
      { time: "2026-08-15 02:00", event: "Database backup completed", actor: "system", tenant: "All", status: "Info" },
      { time: "2026-08-14 22:31", event: "Tenant suspended", actor: "Ishaan Verma", tenant: "VetCare Nagpur", status: "Warning" },
    ],
    createLabel: "Log Incident",
    fields: [
      { key: "time", label: "Time", type: "text", required: true, placeholder: "2026-08-15 12:00" },
      { key: "event", label: "Event", type: "text", required: true },
      { key: "actor", label: "Actor", type: "text" },
      { key: "tenant", label: "Tenant", type: "text" },
      { key: "status", label: "Severity", type: "select", options: ["Info", "Warning", "Critical"], required: true },
    ],
  },

  identity: {
    id: "identity",
    icon: "ShieldCheck",
    title: "Identity, Roles & Access",
    subtitle: "Manage branch staff accounts and permissions",
    kpis: [
      { label: "Active staff accounts", value: "0", trend: "0 new", trendTone: "flat" },
      { label: "Roles configured", value: "0", trend: "standard", trendTone: "flat" },
      { label: "Pending invites", value: "0", trend: "none pending", trendTone: "flat" },
      { label: "Locked accounts", value: "0", trend: "none locked", trendTone: "flat" },
    ],
    columns: [
      { key: "name", label: "Staff" },
      { key: "role", label: "Role" },
      { key: "dept", label: "Department" },
      { key: "phone", label: "Phone" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "Add Staff",
    fields: [
      { key: "name", label: "Full name", type: "text", required: true },
      { key: "role", label: "Role", type: "select", options: ["Admin", "Veterinarian", "Receptionist", "Accountant", "Lab Technician", "Groomer"], required: true },
      { key: "dept", label: "Department", type: "text", required: true },
      { key: "phone", label: "Phone", type: "text", required: true },
      { key: "status", label: "Status", type: "select", options: ["Active", "Invited", "Locked"], required: true },
    ],
  },

  "crm-pets": {
    id: "crm-pets",
    icon: "PawPrint",
    title: "Pet & Owner CRM",
    subtitle: "Registered pets, owner records and visit history",
    kpis: [
      { label: "Registered pets", value: "0", trend: "0 today", trendTone: "flat" },
      { label: "Owners", value: "0", trend: "0 today", trendTone: "flat" },
      { label: "Visits this month", value: "0", trend: "0%", trendTone: "flat" },
      { label: "Vaccination due", value: "0", trend: "none due", trendTone: "flat" },
    ],
    seriesLabel: "New registrations",
    series: series(0, 0, 0, 0, 0, 0),
    columns: [
      { key: "petId", label: "Pet ID" },
      { key: "pet", label: "Pet" },
      { key: "species", label: "Species" },
      { key: "age", label: "Age", align: "right" },
      { key: "owner", label: "Owner" },
      { key: "phone", label: "Phone" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "Register Pet",
    fields: [
      { key: "petId", label: "Pet ID", type: "text", required: true, placeholder: "PET00000" },
      { key: "pet", label: "Pet name", type: "text", required: true },
      { key: "species", label: "Species", type: "select", options: ["Dog", "Cat", "Bird", "Rabbit", "Other"], required: true },
      { key: "age", label: "Age (years)", type: "number", required: true },
      { key: "owner", label: "Owner name", type: "text", required: true },
      { key: "phone", label: "Phone", type: "text", required: true },
      { key: "status", label: "Status", type: "select", options: ["Active", "Vaccination due", "Inactive"], required: true },
    ],
  },

  appointments: {
    id: "appointments",
    icon: "CalendarClock",
    title: "Appointments & Queue",
    subtitle: "Doctor schedules, bookings and the live queue",
    kpis: [
      { label: "In queue now", value: "7", trend: "+2 vs yesterday", trendTone: "up" },
      { label: "Today's appointments", value: "42", trend: "16 remaining", trendTone: "flat" },
      { label: "Avg. wait", value: "12 min", trend: "-3 min", trendTone: "up" },
      { label: "No-shows", value: "3", trend: "+1", trendTone: "down" },
    ],
    seriesLabel: "Appointments per month",
    series: series(842, 901, 934, 1012, 988, 1104),
    columns: [
      { key: "token", label: "Token" },
      { key: "time", label: "Slot" },
      { key: "pet", label: "Pet" },
      { key: "owner", label: "Owner" },
      { key: "doctor", label: "Doctor" },
      { key: "type", label: "Type" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { token: "A-101", time: "09:30", pet: "Bruno", owner: "Tariq Hussain", doctor: "Dr. Rao", type: "Consultation", status: "Completed" },
      { token: "A-102", time: "10:00", pet: "Simba", owner: "Nalini Prasad", doctor: "Dr. Rao", type: "Vaccination", status: "Completed" },
      { token: "A-103", time: "10:30", pet: "Coco", owner: "Deepika Iyer", doctor: "Dr. Hussain", type: "Follow-up", status: "In consultation" },
      { token: "A-104", time: "11:00", pet: "Kiwi", owner: "Rajan Kumar", doctor: "Dr. Hussain", type: "Consultation", status: "Waiting" },
      { token: "A-105", time: "11:15", pet: "Milo", owner: "Ananya Sharma", doctor: "Dr. Rao", type: "Dental", status: "Waiting" },
      { token: "A-106", time: "11:45", pet: "Luna", owner: "Vikram Shetty", doctor: "Dr. Rao", type: "Consultation", status: "Waiting" },
      { token: "A-107", time: "12:15", pet: "Rocky", owner: "Kavitha Nair", doctor: "Dr. Hussain", type: "Surgery review", status: "Scheduled" },
    ],
    createLabel: "Book Appointment",
    fields: [
      { key: "token", label: "Token", type: "text", required: true, placeholder: "A-108" },
      { key: "time", label: "Slot", type: "text", required: true, placeholder: "12:45" },
      { key: "pet", label: "Pet", type: "text", required: true },
      { key: "owner", label: "Owner", type: "text", required: true },
      { key: "doctor", label: "Doctor", type: "select", options: ["Dr. Rao", "Dr. Hussain", "Dr. Pillai"], required: true },
      { key: "type", label: "Visit type", type: "select", options: ["Consultation", "Vaccination", "Follow-up", "Dental", "Surgery review"], required: true },
      { key: "status", label: "Status", type: "select", options: ["Scheduled", "Waiting", "In consultation", "Completed", "No-show"], required: true },
    ],
  },

  opd: {
    id: "opd",
    icon: "Stethoscope",
    title: "OPD Front-Desk",
    subtitle: "Check-ins, encounters and encounter billing status",
    kpis: [
      { label: "Open encounters", value: "12", trend: "+3", trendTone: "down" },
      { label: "Checked-in today", value: "28", trend: "+5", trendTone: "up" },
      { label: "Avg. consult time", value: "18 min", trend: "-2 min", trendTone: "up" },
      { label: "Unbilled encounters", value: "6", trend: "₹14,200", trendTone: "down" },
    ],
    columns: [
      { key: "enc", label: "Encounter" },
      { key: "pet", label: "Pet" },
      { key: "doctor", label: "Doctor" },
      { key: "complaint", label: "Complaint" },
      { key: "amount", label: "Charges", align: "right", kind: "money" },
      { key: "status", label: "Billing", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { enc: "ENC-4411", pet: "Bruno", doctor: "Dr. Rao", complaint: "Limping hind leg", amount: 850, status: "Billed" },
      { enc: "ENC-4412", pet: "Simba", doctor: "Dr. Rao", complaint: "Annual vaccine", amount: 1200, status: "Billed" },
      { enc: "ENC-4413", pet: "Coco", doctor: "Dr. Hussain", complaint: "Skin allergy", amount: 1650, status: "Unbilled" },
      { enc: "ENC-4414", pet: "Kiwi", doctor: "Dr. Hussain", complaint: "Feather loss", amount: 600, status: "Unbilled" },
      { enc: "ENC-4415", pet: "Milo", doctor: "Dr. Rao", complaint: "Dental scaling", amount: 3200, status: "Open" },
    ],
    createLabel: "New Encounter",
    fields: [
      { key: "enc", label: "Encounter ID", type: "text", required: true, placeholder: "ENC-4416" },
      { key: "pet", label: "Pet", type: "text", required: true },
      { key: "doctor", label: "Doctor", type: "select", options: ["Dr. Rao", "Dr. Hussain", "Dr. Pillai"], required: true },
      { key: "complaint", label: "Presenting complaint", type: "text", required: true },
      { key: "amount", label: "Charges", type: "number", required: true },
      { key: "status", label: "Billing status", type: "select", options: ["Open", "Unbilled", "Billed"], required: true },
    ],
  },

  laboratory: {
    id: "laboratory",
    icon: "FlaskConical",
    title: "Laboratory",
    subtitle: "Orders, test profiles and diagnostic reports",
    kpis: [
      { label: "Pending reports", value: "0", trend: "0 urgent", trendTone: "flat" },
      { label: "Orders today", value: "0", trend: "0 vs yesterday", trendTone: "flat" },
      { label: "Samples in transit", value: "0", trend: "none", trendTone: "flat" },
      { label: "Avg. TAT", value: "—", trend: "—", trendTone: "flat" },
    ],
    columns: [
      { key: "order", label: "Order" },
      { key: "pet", label: "Pet" },
      { key: "test", label: "Test" },
      { key: "sample", label: "Sample" },
      { key: "collected", label: "Collected" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "Create Lab Order",
    fields: [
      { key: "order", label: "Order ID", type: "text", required: true, placeholder: "LAB-8806" },
      { key: "pet", label: "Pet", type: "text", required: true },
      { key: "test", label: "Test", type: "text", required: true },
      { key: "sample", label: "Sample type", type: "select", options: ["Blood", "Urine", "Skin", "Swab", "Stool"], required: true },
      { key: "collected", label: "Collected at", type: "text", placeholder: "12:15" },
      { key: "status", label: "Status", type: "select", options: ["Pending", "In process", "In transit", "Urgent", "Reported"], required: true },
    ],
  },

  boarding: {
    id: "boarding",
    icon: "Home",
    title: "Boarding",
    subtitle: "Bookings, check-in/out and kennel occupancy",
    kpis: [
      { label: "Occupied kennels", value: "0", trend: "0% occupancy", trendTone: "flat" },
      { label: "Check-ins today", value: "0", trend: "0 today", trendTone: "flat" },
      { label: "Check-outs today", value: "0", trend: "0 today", trendTone: "flat" },
      { label: "Boarding revenue MTD", value: "₹0", trend: "0%", trendTone: "flat" },
    ],
    seriesLabel: "Occupancy %",
    series: series(0, 0, 0, 0, 0, 0),
    columns: [
      { key: "booking", label: "Booking" },
      { key: "pet", label: "Pet" },
      { key: "kennel", label: "Kennel" },
      { key: "checkIn", label: "Check-in" },
      { key: "checkOut", label: "Check-out" },
      { key: "rate", label: "Rate/day", align: "right", kind: "money" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "New Booking",
    fields: [
      { key: "booking", label: "Booking ID", type: "text", required: true, placeholder: "BRD-316" },
      { key: "pet", label: "Pet", type: "text", required: true },
      { key: "kennel", label: "Kennel", type: "select", options: ["K-01", "K-02", "K-03", "K-04", "K-05", "K-06", "K-07", "K-08"], required: true },
      { key: "checkIn", label: "Check-in", type: "date", required: true },
      { key: "checkOut", label: "Check-out", type: "date", required: true },
      { key: "rate", label: "Rate per day", type: "number", required: true },
      { key: "status", label: "Status", type: "select", options: ["Reserved", "Checked-in", "Staying", "Checked-out"], required: true },
    ],
  },

  swimming: {
    id: "swimming",
    icon: "Waves",
    title: "Swimming",
    subtitle: "Sessions, bookings and memberships",
    kpis: [
      { label: "Sessions today", value: "0", trend: "0 today", trendTone: "flat" },
      { label: "Active memberships", value: "0", trend: "0", trendTone: "flat" },
      { label: "Pool utilisation", value: "0%", trend: "0%", trendTone: "flat" },
      { label: "Revenue MTD", value: "₹0", trend: "0%", trendTone: "flat" },
    ],
    columns: [
      { key: "slot", label: "Slot" },
      { key: "pet", label: "Pet" },
      { key: "trainer", label: "Trainer" },
      { key: "plan", label: "Plan" },
      { key: "fee", label: "Fee", align: "right", kind: "money" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "Book Session",
    fields: [
      { key: "slot", label: "Slot", type: "text", required: true, placeholder: "18:00" },
      { key: "pet", label: "Pet", type: "text", required: true },
      { key: "trainer", label: "Trainer", type: "select", options: ["Arjun Pillai", "Sanjana K"], required: true },
      { key: "plan", label: "Plan", type: "select", options: ["Single session", "Membership", "Hydrotherapy"], required: true },
      { key: "fee", label: "Fee", type: "number", required: true },
      { key: "status", label: "Status", type: "select", options: ["Booked", "In session", "Completed", "Cancelled"], required: true },
    ],
  },

  pharmacy: {
    id: "pharmacy",
    icon: "Pill",
    title: "Pharmacy & Retail",
    subtitle: "Medicine, food and accessory sales",
    kpis: [
      { label: "Sales today", value: "₹0", trend: "0%", trendTone: "flat" },
      { label: "Bills today", value: "0", trend: "0", trendTone: "flat" },
      { label: "Avg. bill value", value: "₹0", trend: "0%", trendTone: "flat" },
      { label: "Out of stock", value: "0", trend: "all stocked", trendTone: "flat" },
    ],
    seriesLabel: "Retail sales (₹ thousand)",
    series: series(0, 0, 0, 0, 0, 0),
    columns: [
      { key: "bill", label: "Bill" },
      { key: "item", label: "Item" },
      { key: "category", label: "Category" },
      { key: "qty", label: "Qty", align: "right" },
      { key: "amount", label: "Amount", align: "right", kind: "money" },
      { key: "status", label: "Payment", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "New Sale",
    fields: [
      { key: "bill", label: "Bill number", type: "text", required: true, placeholder: "RT-9006" },
      { key: "item", label: "Item", type: "text", required: true },
      { key: "category", label: "Category", type: "select", options: ["Medicine", "Food", "Accessory", "Supplement"], required: true },
      { key: "qty", label: "Quantity", type: "number", required: true },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "status", label: "Payment", type: "select", options: ["Paid", "Pending", "Refunded"], required: true },
    ],
  },

  nutrition: {
    id: "nutrition",
    icon: "Bone",
    title: "Food & Nutrition",
    subtitle: "Feeding plans and food purchase tracking",
    kpis: [
      { label: "Reorder due", value: "0", trend: "none", trendTone: "flat" },
      { label: "Active feeding plans", value: "0", trend: "0", trendTone: "flat" },
      { label: "Food sales MTD", value: "₹0", trend: "0%", trendTone: "flat" },
      { label: "Diet reviews due", value: "0", trend: "none", trendTone: "flat" },
    ],
    columns: [
      { key: "plan", label: "Plan" },
      { key: "pet", label: "Pet" },
      { key: "diet", label: "Diet" },
      { key: "qty", label: "Qty/day (g)", align: "right" },
      { key: "review", label: "Next review" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "New Feeding Plan",
    fields: [
      { key: "plan", label: "Plan ID", type: "text", required: true, placeholder: "NUT-206" },
      { key: "pet", label: "Pet", type: "text", required: true },
      { key: "diet", label: "Diet", type: "text", required: true },
      { key: "qty", label: "Quantity per day (g)", type: "number", required: true },
      { key: "review", label: "Next review", type: "date", required: true },
      { key: "status", label: "Status", type: "select", options: ["Active", "Review due", "Closed"], required: true },
    ],
  },

  inventory: {
    id: "inventory",
    icon: "Boxes",
    title: "Inventory & Procurement",
    subtitle: "Stock levels, purchase orders and suppliers",
    kpis: [
      { label: "Low-stock items", value: "0", trend: "none", trendTone: "flat" },
      { label: "Expiring in 30d", value: "0", trend: "none", trendTone: "flat" },
      { label: "Stock value", value: "₹0", trend: "0%", trendTone: "flat" },
      { label: "Supplier outstanding", value: "₹0", trend: "0 invoices", trendTone: "flat" },
    ],
    seriesLabel: "Stock value (₹ lakh)",
    series: series(0, 0, 0, 0, 0, 0),
    columns: [
      { key: "sku", label: "SKU" },
      { key: "item", label: "Item" },
      { key: "supplier", label: "Supplier" },
      { key: "onHand", label: "On hand", align: "right" },
      { key: "reorder", label: "Reorder at", align: "right" },
      { key: "expiry", label: "Expiry" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "Add Stock Item",
    fields: [
      { key: "sku", label: "SKU", type: "text", required: true, placeholder: "SKU-1107" },
      { key: "item", label: "Item name", type: "text", required: true },
      { key: "supplier", label: "Supplier", type: "select", options: ["MedVet Distributors", "BioPharm", "PetNutri", "CareSupplies"], required: true },
      { key: "onHand", label: "On hand", type: "number", required: true },
      { key: "reorder", label: "Reorder level", type: "number", required: true },
      { key: "expiry", label: "Expiry", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["In stock", "Low stock", "Critical", "Expiring"], required: true },
    ],
  },

  billing: {
    id: "billing",
    icon: "Receipt",
    title: "Billing & Payments",
    subtitle: "Invoices, estimates, refunds and collection",
    kpis: [
      { label: "Unpaid invoices", value: "0", trend: "₹0", trendTone: "flat" },
      { label: "Collected today", value: "₹1,24,850", trend: "+12.4%", trendTone: "up" },
      { label: "Unreconciled", value: "17", trend: "gateway sync", trendTone: "flat" },
      { label: "Refunds MTD", value: "₹6,400", trend: "3 requests", trendTone: "flat" },
    ],
    seriesLabel: "Collections (₹ lakh)",
    series: series(18.2, 19.4, 20.1, 20.8, 21.0, 21.6),
    columns: [
      { key: "invoice", label: "Invoice" },
      { key: "owner", label: "Owner" },
      { key: "pet", label: "Pet" },
      { key: "dept", label: "Department" },
      { key: "amount", label: "Amount", align: "right", kind: "money" },
      { key: "mode", label: "Mode" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { invoice: "INV-20481", owner: "Tariq Hussain", pet: "Bruno", dept: "OPD", amount: 850, mode: "UPI", status: "Paid" },
      { invoice: "INV-20482", owner: "Nalini Prasad", pet: "Simba", dept: "Pharmacy", amount: 3200, mode: "Card", status: "Paid" },
      { invoice: "INV-20483", owner: "Deepika Iyer", pet: "Coco", dept: "Laboratory", amount: 1650, mode: "—", status: "Unpaid" },
      { invoice: "INV-20484", owner: "Rajan Kumar", pet: "Kiwi", dept: "OPD", amount: 600, mode: "—", status: "Unpaid" },
      { invoice: "INV-20485", owner: "Vikram Shetty", pet: "Luna", dept: "Boarding", amount: 4500, mode: "Cash", status: "Partially paid" },
      { invoice: "INV-20486", owner: "Ananya Sharma", pet: "Milo", dept: "Swimming", amount: 650, mode: "UPI", status: "Unreconciled" },
    ],
    createLabel: "Raise Invoice",
    fields: [
      { key: "invoice", label: "Invoice no.", type: "text", required: true, placeholder: "INV-20487" },
      { key: "owner", label: "Owner", type: "text", required: true },
      { key: "pet", label: "Pet", type: "text", required: true },
      { key: "dept", label: "Department", type: "select", options: ["OPD", "Laboratory", "Pharmacy", "Boarding", "Swimming"], required: true },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "mode", label: "Payment mode", type: "select", options: ["Cash", "UPI", "Card", "—"] },
      { key: "status", label: "Status", type: "select", options: ["Paid", "Unpaid", "Partially paid", "Unreconciled", "Refunded"], required: true },
    ],
  },

  accounting: {
    id: "accounting",
    icon: "Wallet",
    title: "Accounting & Finance",
    subtitle: "Ledgers, P&L, balance sheet, GST and TDS",
    kpis: [
      { label: "Net revenue MTD", value: "₹0", trend: "0%", trendTone: "flat" },
      { label: "Expenses MTD", value: "₹0", trend: "0%", trendTone: "flat" },
      { label: "Cash & bank", value: "₹0", trend: "0%", trendTone: "flat" },
      { label: "GST payable", value: "₹0", trend: "none due", trendTone: "flat" },
    ],
    seriesLabel: "Net revenue (₹ lakh)",
    series: series(0, 0, 0, 0, 0, 0),
    columns: [
      { key: "entry", label: "Entry" },
      { key: "date", label: "Date" },
      { key: "ledger", label: "Ledger" },
      { key: "narration", label: "Narration" },
      { key: "amount", label: "Amount", align: "right", kind: "money" },
      { key: "status", label: "Type", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "New Journal Entry",
    fields: [
      { key: "entry", label: "Entry no.", type: "text", required: true, placeholder: "JV-3306" },
      { key: "date", label: "Date", type: "date", required: true },
      { key: "ledger", label: "Ledger", type: "text", required: true },
      { key: "narration", label: "Narration", type: "text", required: true },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "status", label: "Type", type: "select", options: ["Credit", "Debit", "Liability"], required: true },
    ],
  },

  hrms: {
    id: "hrms",
    icon: "Users",
    title: "HRMS",
    subtitle: "Staff attendance, leave and payroll status",
    kpis: [
      { label: "On leave today", value: "0", trend: "0 approved", trendTone: "flat" },
      { label: "Present", value: "0", trend: "0 rostered", trendTone: "flat" },
      { label: "Late marks (MTD)", value: "0", trend: "0", trendTone: "flat" },
      { label: "Payroll due", value: "—", trend: "0 employees", trendTone: "flat" },
    ],
    columns: [
      { key: "emp", label: "Employee" },
      { key: "dept", label: "Department" },
      { key: "shift", label: "Shift" },
      { key: "inTime", label: "In" },
      { key: "hours", label: "Hours", align: "right" },
      { key: "status", label: "Attendance", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "Mark Attendance",
    fields: [
      { key: "emp", label: "Employee", type: "text", required: true },
      { key: "dept", label: "Department", type: "text", required: true },
      { key: "shift", label: "Shift", type: "select", options: ["Morning", "Evening", "Night"], required: true },
      { key: "inTime", label: "In time", type: "text", placeholder: "09:00" },
      { key: "hours", label: "Hours", type: "number" },
      { key: "status", label: "Attendance", type: "select", options: ["Present", "Late", "On leave", "Absent"], required: true },
    ],
  },

  payroll: {
    id: "payroll",
    icon: "Users",
    title: "HRMS — Payroll",
    subtitle: "Salary runs, advances and incentives",
    kpis: [
      { label: "Payroll due date", value: "—", trend: "0 employees", trendTone: "flat" },
      { label: "Gross payroll", value: "₹0", trend: "₹0", trendTone: "flat" },
      { label: "Advances pending", value: "₹0", trend: "0 requests", trendTone: "flat" },
      { label: "TDS deducted", value: "₹0", trend: "none", trendTone: "flat" },
    ],
    seriesLabel: "Payroll cost (₹ lakh)",
    series: series(0, 0, 0, 0, 0, 0),
    columns: [
      { key: "emp", label: "Employee" },
      { key: "role", label: "Role" },
      { key: "gross", label: "Gross", align: "right", kind: "money" },
      { key: "deduction", label: "Deductions", align: "right", kind: "money" },
      { key: "net", label: "Net pay", align: "right", kind: "money" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "Add Payroll Line",
    fields: [
      { key: "emp", label: "Employee", type: "text", required: true },
      { key: "role", label: "Role", type: "text", required: true },
      { key: "gross", label: "Gross", type: "number", required: true },
      { key: "deduction", label: "Deductions", type: "number", required: true },
      { key: "net", label: "Net pay", type: "number", required: true },
      { key: "status", label: "Status", type: "select", options: ["Approved", "Pending", "Hold", "Paid"], required: true },
    ],
  },

  marketing: {
    id: "marketing",
    icon: "Megaphone",
    title: "CRM & Marketing",
    subtitle: "Reminders, campaigns and loyalty programs",
    kpis: [
      { label: "Reminders due today", value: "0", trend: "0 sent", trendTone: "flat" },
      { label: "Active campaigns", value: "0", trend: "0", trendTone: "flat" },
      { label: "Loyalty members", value: "0", trend: "0", trendTone: "flat" },
      { label: "Response rate", value: "0%", trend: "0%", trendTone: "flat" },
    ],
    columns: [
      { key: "name", label: "Campaign / Reminder" },
      { key: "channel", label: "Channel" },
      { key: "audience", label: "Audience" },
      { key: "sent", label: "Sent", align: "right" },
      { key: "opened", label: "Opened", align: "right" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "New Campaign",
    fields: [
      { key: "name", label: "Campaign name", type: "text", required: true },
      { key: "channel", label: "Channel", type: "select", options: ["WhatsApp", "SMS", "Email"], required: true },
      { key: "audience", label: "Audience", type: "text", required: true },
      { key: "sent", label: "Sent", type: "number" },
      { key: "opened", label: "Opened", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["Scheduled", "Running", "Completed", "Paused"], required: true },
    ],
  },

  documents: {
    id: "documents",
    icon: "FileText",
    title: "Documents & Media",
    subtitle: "Reports, X-rays and consent forms",
    kpis: [
      { label: "Uploaded this week", value: "0", trend: "0", trendTone: "flat" },
      { label: "Pending signature", value: "0", trend: "none", trendTone: "flat" },
      { label: "Storage used", value: "0 GB", trend: "0 GB", trendTone: "flat" },
      { label: "Shared with owners", value: "0", trend: "0", trendTone: "flat" },
    ],
    columns: [
      { key: "doc", label: "Document" },
      { key: "pet", label: "Pet" },
      { key: "type", label: "Type" },
      { key: "size", label: "Size" },
      { key: "uploaded", label: "Uploaded" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "Upload Document",
    fields: [
      { key: "doc", label: "File name", type: "text", required: true },
      { key: "pet", label: "Pet", type: "text", required: true },
      { key: "type", label: "Type", type: "select", options: ["X-ray", "Lab report", "Consent form", "Clinical note", "Invoice copy"], required: true },
      { key: "size", label: "Size", type: "text", placeholder: "1.2 MB" },
      { key: "uploaded", label: "Uploaded", type: "date", required: true },
      { key: "status", label: "Status", type: "select", options: ["Internal", "Shared", "Pending signature"], required: true },
    ],
  },

  communication: {
    id: "communication",
    icon: "MessageSquare",
    title: "Communication Center",
    subtitle: "WhatsApp, SMS and email delivery log",
    kpis: [
      { label: "Messages sent today", value: "0", trend: "0", trendTone: "flat" },
      { label: "Delivered", value: "0%", trend: "0%", trendTone: "flat" },
      { label: "Unread replies", value: "0", trend: "none", trendTone: "flat" },
      { label: "Failed", value: "0", trend: "0", trendTone: "flat" },
    ],
    columns: [
      { key: "time", label: "Time" },
      { key: "owner", label: "Owner" },
      { key: "channel", label: "Channel" },
      { key: "message", label: "Message" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "Send Message",
    fields: [
      { key: "time", label: "Time", type: "text", required: true, placeholder: "13:00" },
      { key: "owner", label: "Owner", type: "text", required: true },
      { key: "channel", label: "Channel", type: "select", options: ["WhatsApp", "SMS", "Email"], required: true },
      { key: "message", label: "Message", type: "text", required: true },
      { key: "status", label: "Status", type: "select", options: ["Delivered", "Read", "Unread", "Failed"], required: true },
    ],
  },

  reports: {
    id: "reports",
    icon: "BarChart3",
    title: "Reports & Analytics",
    subtitle: "Branch performance and operational reports",
    kpis: [
      { label: "Saved reports", value: "27", trend: "+3", trendTone: "up" },
      { label: "Scheduled", value: "9", trend: "weekly", trendTone: "flat" },
      { label: "Revenue MTD", value: "₹21.6L", trend: "+9.4%", trendTone: "up" },
      { label: "Footfall MTD", value: "1,842", trend: "+7%", trendTone: "up" },
    ],
    seriesLabel: "Branch revenue (₹ lakh)",
    series: series(17.4, 18.9, 19.5, 20.2, 20.4, 21.6),
    columns: [
      { key: "report", label: "Report" },
      { key: "module", label: "Module" },
      { key: "frequency", label: "Frequency" },
      { key: "lastRun", label: "Last run" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { report: "Daily collection summary", module: "Billing", frequency: "Daily", lastRun: "2026-08-15", status: "Scheduled" },
      { report: "Doctor productivity", module: "OPD", frequency: "Weekly", lastRun: "2026-08-11", status: "Scheduled" },
      { report: "Boarding occupancy trend", module: "Boarding", frequency: "Monthly", lastRun: "2026-08-01", status: "Scheduled" },
      { report: "Slow-moving stock", module: "Inventory", frequency: "Monthly", lastRun: "2026-08-01", status: "Draft" },
      { report: "Vaccination compliance", module: "CRM", frequency: "Weekly", lastRun: "2026-08-12", status: "Scheduled" },
    ],
    createLabel: "New Report",
    fields: [
      { key: "report", label: "Report name", type: "text", required: true },
      { key: "module", label: "Module", type: "text", required: true },
      { key: "frequency", label: "Frequency", type: "select", options: ["Daily", "Weekly", "Monthly"], required: true },
      { key: "lastRun", label: "Last run", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["Scheduled", "Draft", "Paused"], required: true },
    ],
  },

  "reports-frontdesk": {
    id: "reports-frontdesk",
    icon: "BarChart3",
    title: "Reports (Front-Desk)",
    subtitle: "Daily registration and footfall summary",
    kpis: [
      { label: "Today's footfall", value: "68", trend: "+9", trendTone: "up" },
      { label: "New registrations", value: "9", trend: "+4", trendTone: "up" },
      { label: "Walk-ins", value: "21", trend: "31% of visits", trendTone: "flat" },
      { label: "Collections at desk", value: "₹86,400", trend: "+6%", trendTone: "up" },
    ],
    seriesLabel: "Daily footfall",
    series: [
      { name: "Mon", value: 54 },
      { name: "Tue", value: 61 },
      { name: "Wed", value: 58 },
      { name: "Thu", value: 72 },
      { name: "Fri", value: 66 },
      { name: "Sat", value: 68 },
    ],
    columns: [
      { key: "hour", label: "Hour" },
      { key: "walkIns", label: "Walk-ins", align: "right" },
      { key: "booked", label: "Booked", align: "right" },
      { key: "registrations", label: "New regs", align: "right" },
      { key: "collections", label: "Collections", align: "right", kind: "money" },
    ],
    rows: [
      { hour: "09:00 – 11:00", walkIns: 6, booked: 12, registrations: 3, collections: 18400 },
      { hour: "11:00 – 13:00", walkIns: 8, booked: 14, registrations: 2, collections: 26200 },
      { hour: "13:00 – 15:00", walkIns: 3, booked: 7, registrations: 1, collections: 11800 },
      { hour: "15:00 – 17:00", walkIns: 4, booked: 11, registrations: 3, collections: 30000 },
    ],
    createLabel: "Add Slot Row",
    fields: [
      { key: "hour", label: "Hour band", type: "text", required: true, placeholder: "17:00 – 19:00" },
      { key: "walkIns", label: "Walk-ins", type: "number", required: true },
      { key: "booked", label: "Booked", type: "number", required: true },
      { key: "registrations", label: "New registrations", type: "number", required: true },
      { key: "collections", label: "Collections", type: "number", required: true },
    ],
  },

  "reports-finance": {
    id: "reports-finance",
    icon: "BarChart3",
    title: "Reports & Analytics (Financial)",
    subtitle: "Department and branch profitability reports",
    kpis: [
      { label: "Reports scheduled", value: "8", trend: "monthly", trendTone: "flat" },
      { label: "Gross margin", value: "57.4%", trend: "+1.2%", trendTone: "up" },
      { label: "Top department", value: "Pharmacy", trend: "₹6.2L", trendTone: "up" },
      { label: "Loss-making units", value: "1", trend: "Swimming", trendTone: "down" },
    ],
    seriesLabel: "Profit (₹ lakh)",
    series: series(8.1, 9.0, 9.4, 10.1, 10.4, 11.2),
    columns: [
      { key: "dept", label: "Department" },
      { key: "revenue", label: "Revenue", align: "right", kind: "money" },
      { key: "cost", label: "Cost", align: "right", kind: "money" },
      { key: "margin", label: "Margin" },
      { key: "status", label: "Trend", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { dept: "OPD", revenue: 640000, cost: 240000, margin: "62.5%", status: "Growing" },
      { dept: "Pharmacy", revenue: 620000, cost: 380000, margin: "38.7%", status: "Growing" },
      { dept: "Laboratory", revenue: 410000, cost: 150000, margin: "63.4%", status: "Stable" },
      { dept: "Boarding", revenue: 340000, cost: 190000, margin: "44.1%", status: "Stable" },
      { dept: "Swimming", revenue: 110000, cost: 128000, margin: "-16.4%", status: "Declining" },
    ],
    createLabel: "Add Department",
    fields: [
      { key: "dept", label: "Department", type: "text", required: true },
      { key: "revenue", label: "Revenue", type: "number", required: true },
      { key: "cost", label: "Cost", type: "number", required: true },
      { key: "margin", label: "Margin", type: "text", required: true },
      { key: "status", label: "Trend", type: "select", options: ["Growing", "Stable", "Declining"], required: true },
    ],
  },

  integrations: {
    id: "integrations",
    icon: "Plug",
    title: "Integration Hub & Settings (Branch)",
    subtitle: "Branch-level service catalogue and configuration",
    kpis: [
      { label: "Active integrations", value: "0", trend: "none", trendTone: "flat" },
      { label: "Service catalogue items", value: "0", trend: "0", trendTone: "flat" },
      { label: "Tax profiles", value: "0", trend: "none", trendTone: "flat" },
      { label: "Printers configured", value: "0", trend: "none", trendTone: "flat" },
    ],
    columns: [
      { key: "name", label: "Setting / Integration" },
      { key: "type", label: "Type" },
      { key: "value", label: "Configuration" },
      { key: "updated", label: "Updated" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [],
    createLabel: "Add Integration",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "type", label: "Type", type: "select", options: ["Messaging", "Payments", "Compliance", "Hardware", "Scheduling"], required: true },
      { key: "value", label: "Configuration", type: "text", required: true },
      { key: "updated", label: "Updated", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["Connected", "Disabled", "Failing"], required: true },
    ],
  },
};

export function getWorkspace(id: string): Workspace | undefined {
  return WORKSPACES[id];
}
