import type { Kpi } from "./config";

export type FieldType = "text" | "number" | "date" | "select";

export interface Field {
  key: string;
  label: string;
  type: FieldType;
  options?: string[];
  required?: boolean;
  placeholder?: string;
}

export interface Column {
  key: string;
  label: string;
  align?: "left" | "right";
  kind?: "text" | "status" | "money";
}

export type Row = Record<string, string | number>;

export interface Workspace {
  id: string;
  icon: string;
  title: string;
  subtitle: string;
  kpis: Kpi[];
  columns: Column[];
  rows: Row[];
  fields: Field[];
  createLabel: string;
  /** key of the column that carries a status value */
  statusKey?: string;
  /** monthly series for the trend chart */
  series?: { name: string; value: number }[];
  seriesLabel?: string;
}

const months = ["Mar", "Apr", "May", "Jun", "Jul", "Aug"];
const series = (...v: number[]) => months.map((name, i) => ({ name, value: v[i] ?? 0 }));

export const WORKSPACES: Record<string, Workspace> = {
  tenants: {
    id: "tenants",
    icon: "Building2",
    title: "Platform & Tenant Administration",
    subtitle: "Onboard and configure clinic tenants and branches",
    kpis: [
      { label: "Tenants active", value: "38", trend: "+3 this month", trendTone: "up" },
      { label: "Branches", value: "112", trend: "+7", trendTone: "up" },
      { label: "Trials running", value: "5", trend: "2 expiring", trendTone: "flat" },
      { label: "Suspended", value: "1", trend: "payment failed", trendTone: "down" },
    ],
    seriesLabel: "Tenants onboarded",
    series: series(24, 27, 30, 33, 35, 38),
    columns: [
      { key: "name", label: "Tenant" },
      { key: "code", label: "Tenant ID" },
      { key: "branches", label: "Branches", align: "right" },
      { key: "plan", label: "Plan" },
      { key: "status", label: "Status", kind: "status" },
      { key: "since", label: "Onboarded" },
    ],
    statusKey: "status",
    rows: [
      { name: "Paws & Claws", code: "TEN-1001", branches: 6, plan: "Enterprise", status: "Active", since: "2024-03-11" },
      { name: "PetWell Group", code: "TEN-1002", branches: 4, plan: "Growth", status: "Active", since: "2024-07-02" },
      { name: "Happy Tails", code: "TEN-1003", branches: 2, plan: "Starter", status: "Trial", since: "2026-07-28" },
      { name: "VetCare Nagpur", code: "TEN-1004", branches: 1, plan: "Starter", status: "Suspended", since: "2025-01-19" },
      { name: "Animalia Clinics", code: "TEN-1005", branches: 9, plan: "Enterprise", status: "Active", since: "2023-11-05" },
    ],
    createLabel: "Onboard Tenant",
    fields: [
      { key: "name", label: "Tenant name", type: "text", required: true, placeholder: "Clinic group name" },
      { key: "code", label: "Tenant ID", type: "text", required: true, placeholder: "TEN-1006" },
      { key: "branches", label: "Branches", type: "number", required: true },
      { key: "plan", label: "Plan", type: "select", options: ["Starter", "Growth", "Enterprise"], required: true },
      { key: "status", label: "Status", type: "select", options: ["Active", "Trial", "Suspended"], required: true },
      { key: "since", label: "Onboarded", type: "date", required: true },
    ],
  },

  subscriptions: {
    id: "subscriptions",
    icon: "CreditCard",
    title: "Subscription & SaaS Administration",
    subtitle: "Plans, entitlements and billing per tenant",
    kpis: [
      { label: "MRR", value: "₹18.4L", trend: "+6.2%", trendTone: "up" },
      { label: "Renewals this week", value: "6", trend: "2 overdue", trendTone: "down" },
      { label: "Churn (90d)", value: "1.8%", trend: "-0.4%", trendTone: "up" },
      { label: "Avg. seats/tenant", value: "27", trend: "+2", trendTone: "up" },
    ],
    seriesLabel: "MRR (₹ lakh)",
    series: series(13.1, 14.4, 15.2, 16.6, 17.3, 18.4),
    columns: [
      { key: "tenant", label: "Tenant" },
      { key: "plan", label: "Plan" },
      { key: "seats", label: "Seats", align: "right" },
      { key: "amount", label: "Monthly", align: "right", kind: "money" },
      { key: "renewal", label: "Renews" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { tenant: "Paws & Claws", plan: "Enterprise", seats: 64, amount: 74000, renewal: "2026-08-20", status: "Active" },
      { tenant: "PetWell Group", plan: "Growth", seats: 32, amount: 38000, renewal: "2026-08-18", status: "Due" },
      { tenant: "Happy Tails", plan: "Starter", seats: 8, amount: 9000, renewal: "2026-08-27", status: "Trial" },
      { tenant: "VetCare Nagpur", plan: "Starter", seats: 6, amount: 9000, renewal: "2026-08-09", status: "Overdue" },
      { tenant: "Animalia Clinics", plan: "Enterprise", seats: 91, amount: 108000, renewal: "2026-09-01", status: "Active" },
    ],
    createLabel: "New Subscription",
    fields: [
      { key: "tenant", label: "Tenant", type: "text", required: true },
      { key: "plan", label: "Plan", type: "select", options: ["Starter", "Growth", "Enterprise"], required: true },
      { key: "seats", label: "Seats", type: "number", required: true },
      { key: "amount", label: "Monthly amount", type: "number", required: true },
      { key: "renewal", label: "Renewal date", type: "date", required: true },
      { key: "status", label: "Status", type: "select", options: ["Active", "Due", "Trial", "Overdue"], required: true },
    ],
  },

  "identity-global": {
    id: "identity-global",
    icon: "ShieldCheck",
    title: "Identity & Access (Global)",
    subtitle: "Global roles, permission templates and security policy",
    kpis: [
      { label: "Admins across tenants", value: "74", trend: "+5", trendTone: "up" },
      { label: "Permission templates", value: "12", trend: "stable", trendTone: "flat" },
      { label: "MFA enforced", value: "86%", trend: "+9%", trendTone: "up" },
      { label: "Dormant accounts", value: "13", trend: "review", trendTone: "down" },
    ],
    columns: [
      { key: "user", label: "User" },
      { key: "tenant", label: "Tenant" },
      { key: "role", label: "Role" },
      { key: "mfa", label: "MFA" },
      { key: "lastSeen", label: "Last active" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { user: "Dr. Ananya Rao", tenant: "Paws & Claws", role: "Admin", mfa: "Enabled", lastSeen: "2026-08-15", status: "Active" },
      { user: "Rahul Menon", tenant: "Paws & Claws", role: "Accountant", mfa: "Enabled", lastSeen: "2026-08-15", status: "Active" },
      { user: "Nalini Prasad", tenant: "PetWell Group", role: "Admin", mfa: "Disabled", lastSeen: "2026-07-30", status: "Review" },
      { user: "Vikram Shetty", tenant: "Animalia Clinics", role: "Admin", mfa: "Enabled", lastSeen: "2026-08-14", status: "Active" },
      { user: "Deepika Iyer", tenant: "Happy Tails", role: "Receptionist", mfa: "Disabled", lastSeen: "2026-05-02", status: "Dormant" },
    ],
    createLabel: "Invite Admin",
    fields: [
      { key: "user", label: "Full name", type: "text", required: true },
      { key: "tenant", label: "Tenant", type: "text", required: true },
      { key: "role", label: "Role", type: "select", options: ["Admin", "Accountant", "Receptionist", "Platform Admin"], required: true },
      { key: "mfa", label: "MFA", type: "select", options: ["Enabled", "Disabled"], required: true },
      { key: "lastSeen", label: "Last active", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["Active", "Review", "Dormant"], required: true },
    ],
  },

  "integrations-global": {
    id: "integrations-global",
    icon: "Plug",
    title: "Integration Hub & Settings (Global)",
    subtitle: "WhatsApp, SMS, payment gateway and GST providers",
    kpis: [
      { label: "Integrations connected", value: "11", trend: "+1", trendTone: "up" },
      { label: "Failing", value: "1", trend: "SMS provider", trendTone: "down" },
      { label: "API calls (24h)", value: "412k", trend: "+4%", trendTone: "up" },
      { label: "Avg. latency", value: "184ms", trend: "-12ms", trendTone: "up" },
    ],
    columns: [
      { key: "provider", label: "Provider" },
      { key: "type", label: "Type" },
      { key: "tenants", label: "Tenants", align: "right" },
      { key: "calls", label: "Calls (24h)", align: "right" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { provider: "WhatsApp Cloud API", type: "Messaging", tenants: 38, calls: 184000, status: "Connected" },
      { provider: "Twilio SMS", type: "Messaging", tenants: 21, calls: 42000, status: "Failing" },
      { provider: "Razorpay", type: "Payments", tenants: 34, calls: 96000, status: "Connected" },
      { provider: "ClearTax GST", type: "Compliance", tenants: 30, calls: 12000, status: "Connected" },
      { provider: "SendGrid", type: "Email", tenants: 29, calls: 78000, status: "Connected" },
    ],
    createLabel: "Connect Provider",
    fields: [
      { key: "provider", label: "Provider", type: "text", required: true },
      { key: "type", label: "Type", type: "select", options: ["Messaging", "Payments", "Compliance", "Email"], required: true },
      { key: "tenants", label: "Tenants enabled", type: "number" },
      { key: "calls", label: "Calls (24h)", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["Connected", "Failing", "Disabled"], required: true },
    ],
  },

  "reports-platform": {
    id: "reports-platform",
    icon: "BarChart3",
    title: "Reports & Analytics (Platform-wide)",
    subtitle: "Cross-tenant usage, revenue and health metrics",
    kpis: [
      { label: "Tenants flagged", value: "4", trend: "+1", trendTone: "down" },
      { label: "Reports scheduled", value: "14", trend: "weekly", trendTone: "flat" },
      { label: "Avg. usage score", value: "72", trend: "+3", trendTone: "up" },
      { label: "Revenue/tenant", value: "₹48.4k", trend: "+5%", trendTone: "up" },
    ],
    seriesLabel: "Platform revenue (₹ lakh)",
    series: series(13.1, 14.4, 15.2, 16.6, 17.3, 18.4),
    columns: [
      { key: "report", label: "Report" },
      { key: "scope", label: "Scope" },
      { key: "frequency", label: "Frequency" },
      { key: "owner", label: "Owner" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { report: "Tenant health scorecard", scope: "All tenants", frequency: "Weekly", owner: "Platform Ops", status: "Scheduled" },
      { report: "Revenue by plan", scope: "All tenants", frequency: "Monthly", owner: "Finance", status: "Scheduled" },
      { report: "Feature adoption", scope: "Enterprise", frequency: "Monthly", owner: "Product", status: "Draft" },
      { report: "Churn risk list", scope: "Starter", frequency: "Weekly", owner: "Success", status: "Scheduled" },
    ],
    createLabel: "New Report",
    fields: [
      { key: "report", label: "Report name", type: "text", required: true },
      { key: "scope", label: "Scope", type: "text", required: true },
      { key: "frequency", label: "Frequency", type: "select", options: ["Daily", "Weekly", "Monthly"], required: true },
      { key: "owner", label: "Owner", type: "text" },
      { key: "status", label: "Status", type: "select", options: ["Scheduled", "Draft", "Paused"], required: true },
    ],
  },

  audit: {
    id: "audit",
    icon: "Activity",
    title: "Audit & System Health",
    subtitle: "Audit trail, backup status and incident log",
    kpis: [
      { label: "Failed jobs / alerts", value: "3", trend: "1 critical", trendTone: "down" },
      { label: "Uptime (30d)", value: "99.98%", trend: "SLA met", trendTone: "up" },
      { label: "Last backup", value: "02:00", trend: "successful", trendTone: "up" },
      { label: "Audit events (24h)", value: "8,412", trend: "+6%", trendTone: "flat" },
    ],
    columns: [
      { key: "time", label: "Time" },
      { key: "event", label: "Event" },
      { key: "actor", label: "Actor" },
      { key: "tenant", label: "Tenant" },
      { key: "status", label: "Severity", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { time: "2026-08-15 11:42", event: "Nightly billing job failed", actor: "system", tenant: "VetCare Nagpur", status: "Critical" },
      { time: "2026-08-15 10:18", event: "Permission template updated", actor: "Ishaan Verma", tenant: "Paws & Claws", status: "Info" },
      { time: "2026-08-15 09:03", event: "SMS provider timeout", actor: "system", tenant: "All", status: "Warning" },
      { time: "2026-08-15 02:00", event: "Database backup completed", actor: "system", tenant: "All", status: "Info" },
      { time: "2026-08-14 22:31", event: "Tenant suspended", actor: "Ishaan Verma", tenant: "VetCare Nagpur", status: "Warning" },
    ],
    createLabel: "Log Incident",
    fields: [
      { key: "time", label: "Time", type: "text", required: true, placeholder: "2026-08-15 12:00" },
      { key: "event", label: "Event", type: "text", required: true },
      { key: "actor", label: "Actor", type: "text" },
      { key: "tenant", label: "Tenant", type: "text" },
      { key: "status", label: "Severity", type: "select", options: ["Info", "Warning", "Critical"], required: true },
    ],
  },

  identity: {
    id: "identity",
    icon: "ShieldCheck",
    title: "Identity, Roles & Access",
    subtitle: "Manage branch staff accounts and permissions",
    kpis: [
      { label: "Active staff accounts", value: "31", trend: "+2", trendTone: "up" },
      { label: "Roles configured", value: "7", trend: "stable", trendTone: "flat" },
      { label: "Pending invites", value: "3", trend: "sent today", trendTone: "flat" },
      { label: "Locked accounts", value: "1", trend: "reset needed", trendTone: "down" },
    ],
    columns: [
      { key: "name", label: "Staff" },
      { key: "role", label: "Role" },
      { key: "dept", label: "Department" },
      { key: "phone", label: "Phone" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { name: "Dr. Ananya Rao", role: "Admin", dept: "Management", phone: "+91 98490 11221", status: "Active" },
      { name: "Dr. Tariq Hussain", role: "Veterinarian", dept: "OPD", phone: "+91 98490 33445", status: "Active" },
      { name: "Kavitha Nair", role: "Receptionist", dept: "Front Desk", phone: "+91 98490 55667", status: "Active" },
      { name: "Rahul Menon", role: "Accountant", dept: "Finance", phone: "+91 98490 77889", status: "Active" },
      { name: "Sunita Bose", role: "Lab Technician", dept: "Laboratory", phone: "+91 98490 99001", status: "Locked" },
      { name: "Arjun Pillai", role: "Groomer", dept: "Swimming", phone: "+91 98490 22334", status: "Invited" },
    ],
    createLabel: "Add Staff",
    fields: [
      { key: "name", label: "Full name", type: "text", required: true },
      { key: "role", label: "Role", type: "select", options: ["Admin", "Veterinarian", "Receptionist", "Accountant", "Lab Technician", "Groomer"], required: true },
      { key: "dept", label: "Department", type: "text", required: true },
      { key: "phone", label: "Phone", type: "text", required: true },
      { key: "status", label: "Status", type: "select", options: ["Active", "Invited", "Locked"], required: true },
    ],
  },

  "crm-pets": {
    id: "crm-pets",
    icon: "PawPrint",
    title: "Pet & Owner CRM",
    subtitle: "Registered pets, owner records and visit history",
    kpis: [
      { label: "Registered pets", value: "3,148", trend: "+9 today", trendTone: "up" },
      { label: "Owners", value: "2,406", trend: "+7 today", trendTone: "up" },
      { label: "Visits this month", value: "912", trend: "+11%", trendTone: "up" },
      { label: "Vaccination due", value: "56", trend: "next 14 days", trendTone: "flat" },
    ],
    seriesLabel: "New registrations",
    series: series(118, 132, 141, 156, 149, 172),
    columns: [
      { key: "petId", label: "Pet ID" },
      { key: "pet", label: "Pet" },
      { key: "species", label: "Species" },
      { key: "age", label: "Age", align: "right" },
      { key: "owner", label: "Owner" },
      { key: "phone", label: "Phone" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { petId: "PET77301", pet: "Bruno", species: "Dog", age: 4, owner: "Tariq Hussain", phone: "+91 90000 11111", status: "Active" },
      { petId: "PETBA599", pet: "Simba", species: "Cat", age: 2, owner: "Nalini Prasad", phone: "+91 90000 22222", status: "Active" },
      { petId: "PET93785", pet: "Coco", species: "Dog", age: 7, owner: "Deepika Iyer", phone: "+91 90000 33333", status: "Vaccination due" },
      { petId: "PETFCD18", pet: "Kiwi", species: "Bird", age: 1, owner: "Rajan Kumar", phone: "+91 90000 44444", status: "Active" },
      { petId: "PETD1BEE", pet: "Milo", species: "Dog", age: 3, owner: "Ananya Sharma", phone: "+91 90000 55555", status: "Active" },
      { petId: "PETDD4B3", pet: "Luna", species: "Cat", age: 5, owner: "Vikram Shetty", phone: "+91 90000 66666", status: "Vaccination due" },
      { petId: "PETBD467", pet: "Rocky", species: "Dog", age: 6, owner: "Kavitha Nair", phone: "+91 90000 77777", status: "Inactive" },
    ],
    createLabel: "Register Pet",
    fields: [
      { key: "petId", label: "Pet ID", type: "text", required: true, placeholder: "PET00000" },
      { key: "pet", label: "Pet name", type: "text", required: true },
      { key: "species", label: "Species", type: "select", options: ["Dog", "Cat", "Bird", "Rabbit", "Other"], required: true },
      { key: "age", label: "Age (years)", type: "number", required: true },
      { key: "owner", label: "Owner name", type: "text", required: true },
      { key: "phone", label: "Phone", type: "text", required: true },
      { key: "status", label: "Status", type: "select", options: ["Active", "Vaccination due", "Inactive"], required: true },
    ],
  },

  appointments: {
    id: "appointments",
    icon: "CalendarClock",
    title: "Appointments & Queue",
    subtitle: "Doctor schedules, bookings and the live queue",
    kpis: [
      { label: "In queue now", value: "7", trend: "+2 vs yesterday", trendTone: "up" },
      { label: "Today's appointments", value: "42", trend: "16 remaining", trendTone: "flat" },
      { label: "Avg. wait", value: "12 min", trend: "-3 min", trendTone: "up" },
      { label: "No-shows", value: "3", trend: "+1", trendTone: "down" },
    ],
    seriesLabel: "Appointments per month",
    series: series(842, 901, 934, 1012, 988, 1104),
    columns: [
      { key: "token", label: "Token" },
      { key: "time", label: "Slot" },
      { key: "pet", label: "Pet" },
      { key: "owner", label: "Owner" },
      { key: "doctor", label: "Doctor" },
      { key: "type", label: "Type" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { token: "A-101", time: "09:30", pet: "Bruno", owner: "Tariq Hussain", doctor: "Dr. Rao", type: "Consultation", status: "Completed" },
      { token: "A-102", time: "10:00", pet: "Simba", owner: "Nalini Prasad", doctor: "Dr. Rao", type: "Vaccination", status: "Completed" },
      { token: "A-103", time: "10:30", pet: "Coco", owner: "Deepika Iyer", doctor: "Dr. Hussain", type: "Follow-up", status: "In consultation" },
      { token: "A-104", time: "11:00", pet: "Kiwi", owner: "Rajan Kumar", doctor: "Dr. Hussain", type: "Consultation", status: "Waiting" },
      { token: "A-105", time: "11:15", pet: "Milo", owner: "Ananya Sharma", doctor: "Dr. Rao", type: "Dental", status: "Waiting" },
      { token: "A-106", time: "11:45", pet: "Luna", owner: "Vikram Shetty", doctor: "Dr. Rao", type: "Consultation", status: "Waiting" },
      { token: "A-107", time: "12:15", pet: "Rocky", owner: "Kavitha Nair", doctor: "Dr. Hussain", type: "Surgery review", status: "Scheduled" },
    ],
    createLabel: "Book Appointment",
    fields: [
      { key: "token", label: "Token", type: "text", required: true, placeholder: "A-108" },
      { key: "time", label: "Slot", type: "text", required: true, placeholder: "12:45" },
      { key: "pet", label: "Pet", type: "text", required: true },
      { key: "owner", label: "Owner", type: "text", required: true },
      { key: "doctor", label: "Doctor", type: "select", options: ["Dr. Rao", "Dr. Hussain", "Dr. Pillai"], required: true },
      { key: "type", label: "Visit type", type: "select", options: ["Consultation", "Vaccination", "Follow-up", "Dental", "Surgery review"], required: true },
      { key: "status", label: "Status", type: "select", options: ["Scheduled", "Waiting", "In consultation", "Completed", "No-show"], required: true },
    ],
  },

  opd: {
    id: "opd",
    icon: "Stethoscope",
    title: "OPD Front-Desk",
    subtitle: "Check-ins, encounters and encounter billing status",
    kpis: [
      { label: "Open encounters", value: "12", trend: "+3", trendTone: "down" },
      { label: "Checked-in today", value: "28", trend: "+5", trendTone: "up" },
      { label: "Avg. consult time", value: "18 min", trend: "-2 min", trendTone: "up" },
      { label: "Unbilled encounters", value: "6", trend: "₹14,200", trendTone: "down" },
    ],
    columns: [
      { key: "enc", label: "Encounter" },
      { key: "pet", label: "Pet" },
      { key: "doctor", label: "Doctor" },
      { key: "complaint", label: "Complaint" },
      { key: "amount", label: "Charges", align: "right", kind: "money" },
      { key: "status", label: "Billing", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { enc: "ENC-4411", pet: "Bruno", doctor: "Dr. Rao", complaint: "Limping hind leg", amount: 850, status: "Billed" },
      { enc: "ENC-4412", pet: "Simba", doctor: "Dr. Rao", complaint: "Annual vaccine", amount: 1200, status: "Billed" },
      { enc: "ENC-4413", pet: "Coco", doctor: "Dr. Hussain", complaint: "Skin allergy", amount: 1650, status: "Unbilled" },
      { enc: "ENC-4414", pet: "Kiwi", doctor: "Dr. Hussain", complaint: "Feather loss", amount: 600, status: "Unbilled" },
      { enc: "ENC-4415", pet: "Milo", doctor: "Dr. Rao", complaint: "Dental scaling", amount: 3200, status: "Open" },
    ],
    createLabel: "New Encounter",
    fields: [
      { key: "enc", label: "Encounter ID", type: "text", required: true, placeholder: "ENC-4416" },
      { key: "pet", label: "Pet", type: "text", required: true },
      { key: "doctor", label: "Doctor", type: "select", options: ["Dr. Rao", "Dr. Hussain", "Dr. Pillai"], required: true },
      { key: "complaint", label: "Presenting complaint", type: "text", required: true },
      { key: "amount", label: "Charges", type: "number", required: true },
      { key: "status", label: "Billing status", type: "select", options: ["Open", "Unbilled", "Billed"], required: true },
    ],
  },

  laboratory: {
    id: "laboratory",
    icon: "FlaskConical",
    title: "Laboratory",
    subtitle: "Orders, sample tracking and report status",
    kpis: [
      { label: "Pending reports", value: "8", trend: "2 urgent", trendTone: "down" },
      { label: "Orders today", value: "14", trend: "+3", trendTone: "up" },
      { label: "Samples in transit", value: "4", trend: "external lab", trendTone: "flat" },
      { label: "Avg. TAT", value: "6.2 hrs", trend: "-40 min", trendTone: "up" },
    ],
    columns: [
      { key: "order", label: "Order" },
      { key: "pet", label: "Pet" },
      { key: "test", label: "Test" },
      { key: "sample", label: "Sample" },
      { key: "collected", label: "Collected" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { order: "LAB-8801", pet: "Bruno", test: "CBC", sample: "Blood", collected: "09:45", status: "Reported" },
      { order: "LAB-8802", pet: "Coco", test: "Skin scrape cytology", sample: "Skin", collected: "10:20", status: "In process" },
      { order: "LAB-8803", pet: "Luna", test: "Renal panel", sample: "Blood", collected: "10:55", status: "Urgent" },
      { order: "LAB-8804", pet: "Milo", test: "Urinalysis", sample: "Urine", collected: "11:10", status: "Pending" },
      { order: "LAB-8805", pet: "Kiwi", test: "Culture & sensitivity", sample: "Swab", collected: "11:35", status: "In transit" },
    ],
    createLabel: "Create Lab Order",
    fields: [
      { key: "order", label: "Order ID", type: "text", required: true, placeholder: "LAB-8806" },
      { key: "pet", label: "Pet", type: "text", required: true },
      { key: "test", label: "Test", type: "text", required: true },
      { key: "sample", label: "Sample type", type: "select", options: ["Blood", "Urine", "Skin", "Swab", "Stool"], required: true },
      { key: "collected", label: "Collected at", type: "text", placeholder: "12:15" },
      { key: "status", label: "Status", type: "select", options: ["Pending", "In process", "In transit", "Urgent", "Reported"], required: true },
    ],
  },

  boarding: {
    id: "boarding",
    icon: "Home",
    title: "Boarding",
    subtitle: "Bookings, check-in/out and kennel occupancy",
    kpis: [
      { label: "Occupied kennels", value: "18 / 23", trend: "78% occupancy", trendTone: "flat" },
      { label: "Check-ins today", value: "5", trend: "+2", trendTone: "up" },
      { label: "Check-outs today", value: "3", trend: "-1", trendTone: "flat" },
      { label: "Boarding revenue MTD", value: "₹3.4L", trend: "+7%", trendTone: "up" },
    ],
    seriesLabel: "Occupancy %",
    series: series(61, 66, 70, 74, 71, 78),
    columns: [
      { key: "booking", label: "Booking" },
      { key: "pet", label: "Pet" },
      { key: "kennel", label: "Kennel" },
      { key: "checkIn", label: "Check-in" },
      { key: "checkOut", label: "Check-out" },
      { key: "rate", label: "Rate/day", align: "right", kind: "money" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { booking: "BRD-311", pet: "Bruno", kennel: "K-04", checkIn: "2026-08-12", checkOut: "2026-08-18", rate: 900, status: "Staying" },
      { booking: "BRD-312", pet: "Luna", kennel: "K-07", checkIn: "2026-08-14", checkOut: "2026-08-16", rate: 750, status: "Staying" },
      { booking: "BRD-313", pet: "Rocky", kennel: "K-11", checkIn: "2026-08-15", checkOut: "2026-08-21", rate: 900, status: "Checked-in" },
      { booking: "BRD-314", pet: "Coco", kennel: "K-02", checkIn: "2026-08-16", checkOut: "2026-08-19", rate: 900, status: "Reserved" },
      { booking: "BRD-315", pet: "Simba", kennel: "K-09", checkIn: "2026-08-09", checkOut: "2026-08-15", rate: 700, status: "Checked-out" },
    ],
    createLabel: "New Booking",
    fields: [
      { key: "booking", label: "Booking ID", type: "text", required: true, placeholder: "BRD-316" },
      { key: "pet", label: "Pet", type: "text", required: true },
      { key: "kennel", label: "Kennel", type: "select", options: ["K-01", "K-02", "K-03", "K-04", "K-05", "K-06", "K-07", "K-08"], required: true },
      { key: "checkIn", label: "Check-in", type: "date", required: true },
      { key: "checkOut", label: "Check-out", type: "date", required: true },
      { key: "rate", label: "Rate per day", type: "number", required: true },
      { key: "status", label: "Status", type: "select", options: ["Reserved", "Checked-in", "Staying", "Checked-out"], required: true },
    ],
  },

  swimming: {
    id: "swimming",
    icon: "Waves",
    title: "Swimming",
    subtitle: "Sessions, bookings and memberships",
    kpis: [
      { label: "Sessions today", value: "11", trend: "+2", trendTone: "up" },
      { label: "Active memberships", value: "64", trend: "+5", trendTone: "up" },
      { label: "Pool utilisation", value: "82%", trend: "+6%", trendTone: "up" },
      { label: "Revenue MTD", value: "₹1.1L", trend: "+4%", trendTone: "up" },
    ],
    columns: [
      { key: "slot", label: "Slot" },
      { key: "pet", label: "Pet" },
      { key: "trainer", label: "Trainer" },
      { key: "plan", label: "Plan" },
      { key: "fee", label: "Fee", align: "right", kind: "money" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { slot: "08:00", pet: "Bruno", trainer: "Arjun Pillai", plan: "Membership", fee: 0, status: "Completed" },
      { slot: "09:00", pet: "Milo", trainer: "Arjun Pillai", plan: "Single session", fee: 650, status: "Completed" },
      { slot: "11:00", pet: "Rocky", trainer: "Sanjana K", plan: "Hydrotherapy", fee: 1200, status: "In session" },
      { slot: "16:00", pet: "Luna", trainer: "Sanjana K", plan: "Single session", fee: 650, status: "Booked" },
      { slot: "17:00", pet: "Coco", trainer: "Arjun Pillai", plan: "Membership", fee: 0, status: "Booked" },
    ],
    createLabel: "Book Session",
    fields: [
      { key: "slot", label: "Slot", type: "text", required: true, placeholder: "18:00" },
      { key: "pet", label: "Pet", type: "text", required: true },
      { key: "trainer", label: "Trainer", type: "select", options: ["Arjun Pillai", "Sanjana K"], required: true },
      { key: "plan", label: "Plan", type: "select", options: ["Single session", "Membership", "Hydrotherapy"], required: true },
      { key: "fee", label: "Fee", type: "number", required: true },
      { key: "status", label: "Status", type: "select", options: ["Booked", "In session", "Completed", "Cancelled"], required: true },
    ],
  },

  pharmacy: {
    id: "pharmacy",
    icon: "Pill",
    title: "Pharmacy & Retail",
    subtitle: "Medicine, food and accessory sales",
    kpis: [
      { label: "Sales today", value: "₹46,200", trend: "+8.1%", trendTone: "up" },
      { label: "Bills today", value: "37", trend: "+4", trendTone: "up" },
      { label: "Avg. bill value", value: "₹1,249", trend: "+3%", trendTone: "up" },
      { label: "Out of stock", value: "6", trend: "reorder now", trendTone: "down" },
    ],
    seriesLabel: "Retail sales (₹ thousand)",
    series: series(980, 1042, 1130, 1088, 1195, 1264),
    columns: [
      { key: "bill", label: "Bill" },
      { key: "item", label: "Item" },
      { key: "category", label: "Category" },
      { key: "qty", label: "Qty", align: "right" },
      { key: "amount", label: "Amount", align: "right", kind: "money" },
      { key: "status", label: "Payment", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { bill: "RT-9001", item: "Amoxicillin 250mg", category: "Medicine", qty: 20, amount: 640, status: "Paid" },
      { bill: "RT-9002", item: "Royal Canin Maxi 4kg", category: "Food", qty: 1, amount: 3200, status: "Paid" },
      { bill: "RT-9003", item: "Tick & flea spot-on", category: "Medicine", qty: 3, amount: 1350, status: "Paid" },
      { bill: "RT-9004", item: "Nylon leash", category: "Accessory", qty: 2, amount: 900, status: "Pending" },
      { bill: "RT-9005", item: "Joint supplement", category: "Supplement", qty: 1, amount: 1450, status: "Paid" },
    ],
    createLabel: "New Sale",
    fields: [
      { key: "bill", label: "Bill number", type: "text", required: true, placeholder: "RT-9006" },
      { key: "item", label: "Item", type: "text", required: true },
      { key: "category", label: "Category", type: "select", options: ["Medicine", "Food", "Accessory", "Supplement"], required: true },
      { key: "qty", label: "Quantity", type: "number", required: true },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "status", label: "Payment", type: "select", options: ["Paid", "Pending", "Refunded"], required: true },
    ],
  },

  nutrition: {
    id: "nutrition",
    icon: "Bone",
    title: "Food & Nutrition",
    subtitle: "Feeding plans and food purchase tracking",
    kpis: [
      { label: "Reorder due", value: "5", trend: "3 critical", trendTone: "down" },
      { label: "Active feeding plans", value: "142", trend: "+8", trendTone: "up" },
      { label: "Food sales MTD", value: "₹2.7L", trend: "+6%", trendTone: "up" },
      { label: "Diet reviews due", value: "12", trend: "this week", trendTone: "flat" },
    ],
    columns: [
      { key: "plan", label: "Plan" },
      { key: "pet", label: "Pet" },
      { key: "diet", label: "Diet" },
      { key: "qty", label: "Qty/day (g)", align: "right" },
      { key: "review", label: "Next review" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { plan: "NUT-201", pet: "Bruno", diet: "Weight control", qty: 320, review: "2026-08-22", status: "Active" },
      { plan: "NUT-202", pet: "Luna", diet: "Renal support", qty: 180, review: "2026-08-18", status: "Review due" },
      { plan: "NUT-203", pet: "Milo", diet: "Puppy growth", qty: 260, review: "2026-09-02", status: "Active" },
      { plan: "NUT-204", pet: "Coco", diet: "Hypoallergenic", qty: 300, review: "2026-08-16", status: "Review due" },
      { plan: "NUT-205", pet: "Simba", diet: "Hairball control", qty: 90, review: "2026-09-10", status: "Active" },
    ],
    createLabel: "New Feeding Plan",
    fields: [
      { key: "plan", label: "Plan ID", type: "text", required: true, placeholder: "NUT-206" },
      { key: "pet", label: "Pet", type: "text", required: true },
      { key: "diet", label: "Diet", type: "text", required: true },
      { key: "qty", label: "Quantity per day (g)", type: "number", required: true },
      { key: "review", label: "Next review", type: "date", required: true },
      { key: "status", label: "Status", type: "select", options: ["Active", "Review due", "Closed"], required: true },
    ],
  },

  inventory: {
    id: "inventory",
    icon: "Boxes",
    title: "Inventory & Procurement",
    subtitle: "Stock levels, purchase orders and suppliers",
    kpis: [
      { label: "Low-stock items", value: "14", trend: "+3", trendTone: "down" },
      { label: "Expiring in 30d", value: "3", trend: "quarantine", trendTone: "down" },
      { label: "Stock value", value: "₹11.6L", trend: "+2.2%", trendTone: "up" },
      { label: "Supplier outstanding", value: "₹2.4L", trend: "4 invoices", trendTone: "flat" },
    ],
    seriesLabel: "Stock value (₹ lakh)",
    series: series(9.8, 10.2, 10.9, 11.1, 11.4, 11.6),
    columns: [
      { key: "sku", label: "SKU" },
      { key: "item", label: "Item" },
      { key: "supplier", label: "Supplier" },
      { key: "onHand", label: "On hand", align: "right" },
      { key: "reorder", label: "Reorder at", align: "right" },
      { key: "expiry", label: "Expiry" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { sku: "SKU-1101", item: "Amoxicillin 250mg", supplier: "MedVet Distributors", onHand: 42, reorder: 60, expiry: "2027-02-01", status: "Low stock" },
      { sku: "SKU-1102", item: "Rabies vaccine", supplier: "BioPharm", onHand: 118, reorder: 50, expiry: "2026-11-14", status: "In stock" },
      { sku: "SKU-1103", item: "IV fluid RL 500ml", supplier: "MedVet Distributors", onHand: 12, reorder: 40, expiry: "2026-09-05", status: "Critical" },
      { sku: "SKU-1104", item: "Royal Canin Maxi 4kg", supplier: "PetNutri", onHand: 26, reorder: 15, expiry: "2027-05-20", status: "In stock" },
      { sku: "SKU-1105", item: "Surgical gloves (box)", supplier: "CareSupplies", onHand: 8, reorder: 20, expiry: "—", status: "Low stock" },
      { sku: "SKU-1106", item: "Deworming syrup", supplier: "BioPharm", onHand: 31, reorder: 25, expiry: "2026-09-01", status: "Expiring" },
    ],
    createLabel: "Add Stock Item",
    fields: [
      { key: "sku", label: "SKU", type: "text", required: true, placeholder: "SKU-1107" },
      { key: "item", label: "Item name", type: "text", required: true },
      { key: "supplier", label: "Supplier", type: "select", options: ["MedVet Distributors", "BioPharm", "PetNutri", "CareSupplies"], required: true },
      { key: "onHand", label: "On hand", type: "number", required: true },
      { key: "reorder", label: "Reorder level", type: "number", required: true },
      { key: "expiry", label: "Expiry", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["In stock", "Low stock", "Critical", "Expiring"], required: true },
    ],
  },

  billing: {
    id: "billing",
    icon: "Receipt",
    title: "Billing & Payments",
    subtitle: "Invoices, estimates, refunds and collection",
    kpis: [
      { label: "Unpaid invoices", value: "23", trend: "₹38,400", trendTone: "down" },
      { label: "Collected today", value: "₹1,24,850", trend: "+12.4%", trendTone: "up" },
      { label: "Unreconciled", value: "17", trend: "gateway sync", trendTone: "flat" },
      { label: "Refunds MTD", value: "₹6,400", trend: "3 requests", trendTone: "flat" },
    ],
    seriesLabel: "Collections (₹ lakh)",
    series: series(18.2, 19.4, 20.1, 20.8, 21.0, 21.6),
    columns: [
      { key: "invoice", label: "Invoice" },
      { key: "owner", label: "Owner" },
      { key: "pet", label: "Pet" },
      { key: "dept", label: "Department" },
      { key: "amount", label: "Amount", align: "right", kind: "money" },
      { key: "mode", label: "Mode" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { invoice: "INV-20481", owner: "Tariq Hussain", pet: "Bruno", dept: "OPD", amount: 850, mode: "UPI", status: "Paid" },
      { invoice: "INV-20482", owner: "Nalini Prasad", pet: "Simba", dept: "Pharmacy", amount: 3200, mode: "Card", status: "Paid" },
      { invoice: "INV-20483", owner: "Deepika Iyer", pet: "Coco", dept: "Laboratory", amount: 1650, mode: "—", status: "Unpaid" },
      { invoice: "INV-20484", owner: "Rajan Kumar", pet: "Kiwi", dept: "OPD", amount: 600, mode: "—", status: "Unpaid" },
      { invoice: "INV-20485", owner: "Vikram Shetty", pet: "Luna", dept: "Boarding", amount: 4500, mode: "Cash", status: "Partially paid" },
      { invoice: "INV-20486", owner: "Ananya Sharma", pet: "Milo", dept: "Swimming", amount: 650, mode: "UPI", status: "Unreconciled" },
    ],
    createLabel: "Raise Invoice",
    fields: [
      { key: "invoice", label: "Invoice no.", type: "text", required: true, placeholder: "INV-20487" },
      { key: "owner", label: "Owner", type: "text", required: true },
      { key: "pet", label: "Pet", type: "text", required: true },
      { key: "dept", label: "Department", type: "select", options: ["OPD", "Laboratory", "Pharmacy", "Boarding", "Swimming"], required: true },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "mode", label: "Payment mode", type: "select", options: ["Cash", "UPI", "Card", "—"] },
      { key: "status", label: "Status", type: "select", options: ["Paid", "Unpaid", "Partially paid", "Unreconciled", "Refunded"], required: true },
    ],
  },

  accounting: {
    id: "accounting",
    icon: "Wallet",
    title: "Accounting & Finance",
    subtitle: "Ledgers, P&L, balance sheet, GST and TDS",
    kpis: [
      { label: "Net revenue MTD", value: "₹21.6L", trend: "+9.4%", trendTone: "up" },
      { label: "Expenses MTD", value: "₹9.2L", trend: "-3.1%", trendTone: "up" },
      { label: "Cash & bank", value: "₹14.3L", trend: "+₹1.1L", trendTone: "up" },
      { label: "GST payable", value: "₹1.8L", trend: "due 20th", trendTone: "flat" },
    ],
    seriesLabel: "Net revenue (₹ lakh)",
    series: series(17.4, 18.9, 19.5, 20.2, 20.4, 21.6),
    columns: [
      { key: "entry", label: "Entry" },
      { key: "date", label: "Date" },
      { key: "ledger", label: "Ledger" },
      { key: "narration", label: "Narration" },
      { key: "amount", label: "Amount", align: "right", kind: "money" },
      { key: "status", label: "Type", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { entry: "JV-3301", date: "2026-08-15", ledger: "Consultation income", narration: "OPD collections", amount: 84500, status: "Credit" },
      { entry: "JV-3302", date: "2026-08-15", ledger: "Pharmacy income", narration: "Retail counter", amount: 46200, status: "Credit" },
      { entry: "JV-3303", date: "2026-08-14", ledger: "Salaries", narration: "Advance — 2 staff", amount: 38000, status: "Debit" },
      { entry: "JV-3304", date: "2026-08-14", ledger: "Supplier payment", narration: "MedVet Distributors", amount: 112000, status: "Debit" },
      { entry: "JV-3305", date: "2026-08-13", ledger: "GST payable", narration: "July output tax", amount: 180000, status: "Liability" },
    ],
    createLabel: "New Journal Entry",
    fields: [
      { key: "entry", label: "Entry no.", type: "text", required: true, placeholder: "JV-3306" },
      { key: "date", label: "Date", type: "date", required: true },
      { key: "ledger", label: "Ledger", type: "text", required: true },
      { key: "narration", label: "Narration", type: "text", required: true },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "status", label: "Type", type: "select", options: ["Credit", "Debit", "Liability"], required: true },
    ],
  },

  hrms: {
    id: "hrms",
    icon: "Users",
    title: "HRMS",
    subtitle: "Staff attendance, leave and payroll status",
    kpis: [
      { label: "On leave today", value: "2", trend: "1 approved", trendTone: "flat" },
      { label: "Present", value: "19", trend: "of 21 rostered", trendTone: "up" },
      { label: "Late marks (MTD)", value: "7", trend: "-2", trendTone: "up" },
      { label: "Payroll due", value: "30 Aug", trend: "31 employees", trendTone: "flat" },
    ],
    columns: [
      { key: "emp", label: "Employee" },
      { key: "dept", label: "Department" },
      { key: "shift", label: "Shift" },
      { key: "inTime", label: "In" },
      { key: "hours", label: "Hours", align: "right" },
      { key: "status", label: "Attendance", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { emp: "Dr. Tariq Hussain", dept: "OPD", shift: "Morning", inTime: "08:52", hours: 8, status: "Present" },
      { emp: "Kavitha Nair", dept: "Front Desk", shift: "Morning", inTime: "09:04", hours: 8, status: "Late" },
      { emp: "Sunita Bose", dept: "Laboratory", shift: "Morning", inTime: "—", hours: 0, status: "On leave" },
      { emp: "Arjun Pillai", dept: "Swimming", shift: "Evening", inTime: "13:58", hours: 6, status: "Present" },
      { emp: "Rahul Menon", dept: "Finance", shift: "Morning", inTime: "09:00", hours: 8, status: "Present" },
    ],
    createLabel: "Mark Attendance",
    fields: [
      { key: "emp", label: "Employee", type: "text", required: true },
      { key: "dept", label: "Department", type: "text", required: true },
      { key: "shift", label: "Shift", type: "select", options: ["Morning", "Evening", "Night"], required: true },
      { key: "inTime", label: "In time", type: "text", placeholder: "09:00" },
      { key: "hours", label: "Hours", type: "number" },
      { key: "status", label: "Attendance", type: "select", options: ["Present", "Late", "On leave", "Absent"], required: true },
    ],
  },

  payroll: {
    id: "payroll",
    icon: "Users",
    title: "HRMS — Payroll",
    subtitle: "Salary runs, advances and incentives",
    kpis: [
      { label: "Payroll due date", value: "30 Aug", trend: "31 employees", trendTone: "flat" },
      { label: "Gross payroll", value: "₹7.4L", trend: "+₹18k", trendTone: "down" },
      { label: "Advances pending", value: "₹64,000", trend: "3 requests", trendTone: "flat" },
      { label: "TDS deducted", value: "₹42,300", trend: "filed", trendTone: "up" },
    ],
    seriesLabel: "Payroll cost (₹ lakh)",
    series: series(6.9, 7.0, 7.1, 7.2, 7.3, 7.4),
    columns: [
      { key: "emp", label: "Employee" },
      { key: "role", label: "Role" },
      { key: "gross", label: "Gross", align: "right", kind: "money" },
      { key: "deduction", label: "Deductions", align: "right", kind: "money" },
      { key: "net", label: "Net pay", align: "right", kind: "money" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { emp: "Dr. Ananya Rao", role: "Admin", gross: 145000, deduction: 18200, net: 126800, status: "Approved" },
      { emp: "Dr. Tariq Hussain", role: "Veterinarian", gross: 118000, deduction: 14100, net: 103900, status: "Approved" },
      { emp: "Kavitha Nair", role: "Receptionist", gross: 38000, deduction: 3200, net: 34800, status: "Pending" },
      { emp: "Sunita Bose", role: "Lab Technician", gross: 42000, deduction: 3600, net: 38400, status: "Pending" },
      { emp: "Arjun Pillai", role: "Groomer", gross: 32000, deduction: 2400, net: 29600, status: "Hold" },
    ],
    createLabel: "Add Payroll Line",
    fields: [
      { key: "emp", label: "Employee", type: "text", required: true },
      { key: "role", label: "Role", type: "text", required: true },
      { key: "gross", label: "Gross", type: "number", required: true },
      { key: "deduction", label: "Deductions", type: "number", required: true },
      { key: "net", label: "Net pay", type: "number", required: true },
      { key: "status", label: "Status", type: "select", options: ["Approved", "Pending", "Hold", "Paid"], required: true },
    ],
  },

  marketing: {
    id: "marketing",
    icon: "Megaphone",
    title: "CRM & Marketing",
    subtitle: "Reminders, campaigns and loyalty programs",
    kpis: [
      { label: "Reminders due today", value: "34", trend: "12 sent", trendTone: "flat" },
      { label: "Active campaigns", value: "5", trend: "+1", trendTone: "up" },
      { label: "Loyalty members", value: "812", trend: "+23", trendTone: "up" },
      { label: "Response rate", value: "38%", trend: "+4%", trendTone: "up" },
    ],
    columns: [
      { key: "name", label: "Campaign / Reminder" },
      { key: "channel", label: "Channel" },
      { key: "audience", label: "Audience" },
      { key: "sent", label: "Sent", align: "right" },
      { key: "opened", label: "Opened", align: "right" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { name: "Vaccination due — Aug", channel: "WhatsApp", audience: "56 pets", sent: 44, opened: 31, status: "Running" },
      { name: "Monsoon deworming offer", channel: "SMS", audience: "1,204 owners", sent: 1204, opened: 402, status: "Completed" },
      { name: "Boarding weekend slots", channel: "WhatsApp", audience: "310 owners", sent: 0, opened: 0, status: "Scheduled" },
      { name: "Loyalty tier upgrade", channel: "Email", audience: "88 owners", sent: 88, opened: 51, status: "Completed" },
      { name: "Swimming membership renewal", channel: "WhatsApp", audience: "64 owners", sent: 22, opened: 14, status: "Running" },
    ],
    createLabel: "New Campaign",
    fields: [
      { key: "name", label: "Campaign name", type: "text", required: true },
      { key: "channel", label: "Channel", type: "select", options: ["WhatsApp", "SMS", "Email"], required: true },
      { key: "audience", label: "Audience", type: "text", required: true },
      { key: "sent", label: "Sent", type: "number" },
      { key: "opened", label: "Opened", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["Scheduled", "Running", "Completed", "Paused"], required: true },
    ],
  },

  documents: {
    id: "documents",
    icon: "FileText",
    title: "Documents & Media",
    subtitle: "Reports, X-rays and consent forms",
    kpis: [
      { label: "Uploaded this week", value: "126", trend: "+18", trendTone: "up" },
      { label: "Pending signature", value: "9", trend: "consent forms", trendTone: "down" },
      { label: "Storage used", value: "48 GB", trend: "of 200 GB", trendTone: "flat" },
      { label: "Shared with owners", value: "72", trend: "+11", trendTone: "up" },
    ],
    columns: [
      { key: "doc", label: "Document" },
      { key: "pet", label: "Pet" },
      { key: "type", label: "Type" },
      { key: "size", label: "Size" },
      { key: "uploaded", label: "Uploaded" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { doc: "Bruno-hip-xray.jpg", pet: "Bruno", type: "X-ray", size: "4.2 MB", uploaded: "2026-08-15", status: "Shared" },
      { doc: "Coco-cytology.pdf", pet: "Coco", type: "Lab report", size: "820 KB", uploaded: "2026-08-15", status: "Internal" },
      { doc: "Milo-consent-dental.pdf", pet: "Milo", type: "Consent form", size: "210 KB", uploaded: "2026-08-14", status: "Pending signature" },
      { doc: "Luna-renal-panel.pdf", pet: "Luna", type: "Lab report", size: "640 KB", uploaded: "2026-08-14", status: "Shared" },
      { doc: "Rocky-surgery-notes.pdf", pet: "Rocky", type: "Clinical note", size: "310 KB", uploaded: "2026-08-13", status: "Internal" },
    ],
    createLabel: "Upload Document",
    fields: [
      { key: "doc", label: "File name", type: "text", required: true },
      { key: "pet", label: "Pet", type: "text", required: true },
      { key: "type", label: "Type", type: "select", options: ["X-ray", "Lab report", "Consent form", "Clinical note", "Invoice copy"], required: true },
      { key: "size", label: "Size", type: "text", placeholder: "1.2 MB" },
      { key: "uploaded", label: "Uploaded", type: "date", required: true },
      { key: "status", label: "Status", type: "select", options: ["Internal", "Shared", "Pending signature"], required: true },
    ],
  },

  communication: {
    id: "communication",
    icon: "MessageSquare",
    title: "Communication Center",
    subtitle: "WhatsApp, SMS and email delivery log",
    kpis: [
      { label: "Messages sent today", value: "418", trend: "+34", trendTone: "up" },
      { label: "Delivered", value: "97.4%", trend: "+0.6%", trendTone: "up" },
      { label: "Unread replies", value: "6", trend: "needs action", trendTone: "down" },
      { label: "Failed", value: "11", trend: "SMS provider", trendTone: "down" },
    ],
    columns: [
      { key: "time", label: "Time" },
      { key: "owner", label: "Owner" },
      { key: "channel", label: "Channel" },
      { key: "message", label: "Message" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { time: "12:41", owner: "Tariq Hussain", channel: "WhatsApp", message: "Bruno's report is ready", status: "Delivered" },
      { time: "12:22", owner: "Deepika Iyer", channel: "WhatsApp", message: "Reply: can I collect at 6pm?", status: "Unread" },
      { time: "11:58", owner: "Rajan Kumar", channel: "SMS", message: "Appointment reminder 11:00", status: "Failed" },
      { time: "11:30", owner: "Vikram Shetty", channel: "Email", message: "Boarding invoice INV-20485", status: "Delivered" },
      { time: "10:47", owner: "Ananya Sharma", channel: "WhatsApp", message: "Swimming slot confirmed", status: "Read" },
    ],
    createLabel: "Send Message",
    fields: [
      { key: "time", label: "Time", type: "text", required: true, placeholder: "13:00" },
      { key: "owner", label: "Owner", type: "text", required: true },
      { key: "channel", label: "Channel", type: "select", options: ["WhatsApp", "SMS", "Email"], required: true },
      { key: "message", label: "Message", type: "text", required: true },
      { key: "status", label: "Status", type: "select", options: ["Delivered", "Read", "Unread", "Failed"], required: true },
    ],
  },

  reports: {
    id: "reports",
    icon: "BarChart3",
    title: "Reports & Analytics",
    subtitle: "Branch performance and operational reports",
    kpis: [
      { label: "Saved reports", value: "27", trend: "+3", trendTone: "up" },
      { label: "Scheduled", value: "9", trend: "weekly", trendTone: "flat" },
      { label: "Revenue MTD", value: "₹21.6L", trend: "+9.4%", trendTone: "up" },
      { label: "Footfall MTD", value: "1,842", trend: "+7%", trendTone: "up" },
    ],
    seriesLabel: "Branch revenue (₹ lakh)",
    series: series(17.4, 18.9, 19.5, 20.2, 20.4, 21.6),
    columns: [
      { key: "report", label: "Report" },
      { key: "module", label: "Module" },
      { key: "frequency", label: "Frequency" },
      { key: "lastRun", label: "Last run" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { report: "Daily collection summary", module: "Billing", frequency: "Daily", lastRun: "2026-08-15", status: "Scheduled" },
      { report: "Doctor productivity", module: "OPD", frequency: "Weekly", lastRun: "2026-08-11", status: "Scheduled" },
      { report: "Boarding occupancy trend", module: "Boarding", frequency: "Monthly", lastRun: "2026-08-01", status: "Scheduled" },
      { report: "Slow-moving stock", module: "Inventory", frequency: "Monthly", lastRun: "2026-08-01", status: "Draft" },
      { report: "Vaccination compliance", module: "CRM", frequency: "Weekly", lastRun: "2026-08-12", status: "Scheduled" },
    ],
    createLabel: "New Report",
    fields: [
      { key: "report", label: "Report name", type: "text", required: true },
      { key: "module", label: "Module", type: "text", required: true },
      { key: "frequency", label: "Frequency", type: "select", options: ["Daily", "Weekly", "Monthly"], required: true },
      { key: "lastRun", label: "Last run", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["Scheduled", "Draft", "Paused"], required: true },
    ],
  },

  "reports-frontdesk": {
    id: "reports-frontdesk",
    icon: "BarChart3",
    title: "Reports (Front-Desk)",
    subtitle: "Daily registration and footfall summary",
    kpis: [
      { label: "Today's footfall", value: "68", trend: "+9", trendTone: "up" },
      { label: "New registrations", value: "9", trend: "+4", trendTone: "up" },
      { label: "Walk-ins", value: "21", trend: "31% of visits", trendTone: "flat" },
      { label: "Collections at desk", value: "₹86,400", trend: "+6%", trendTone: "up" },
    ],
    seriesLabel: "Daily footfall",
    series: [
      { name: "Mon", value: 54 },
      { name: "Tue", value: 61 },
      { name: "Wed", value: 58 },
      { name: "Thu", value: 72 },
      { name: "Fri", value: 66 },
      { name: "Sat", value: 68 },
    ],
    columns: [
      { key: "hour", label: "Hour" },
      { key: "walkIns", label: "Walk-ins", align: "right" },
      { key: "booked", label: "Booked", align: "right" },
      { key: "registrations", label: "New regs", align: "right" },
      { key: "collections", label: "Collections", align: "right", kind: "money" },
    ],
    rows: [
      { hour: "09:00 – 11:00", walkIns: 6, booked: 12, registrations: 3, collections: 18400 },
      { hour: "11:00 – 13:00", walkIns: 8, booked: 14, registrations: 2, collections: 26200 },
      { hour: "13:00 – 15:00", walkIns: 3, booked: 7, registrations: 1, collections: 11800 },
      { hour: "15:00 – 17:00", walkIns: 4, booked: 11, registrations: 3, collections: 30000 },
    ],
    createLabel: "Add Slot Row",
    fields: [
      { key: "hour", label: "Hour band", type: "text", required: true, placeholder: "17:00 – 19:00" },
      { key: "walkIns", label: "Walk-ins", type: "number", required: true },
      { key: "booked", label: "Booked", type: "number", required: true },
      { key: "registrations", label: "New registrations", type: "number", required: true },
      { key: "collections", label: "Collections", type: "number", required: true },
    ],
  },

  "reports-finance": {
    id: "reports-finance",
    icon: "BarChart3",
    title: "Reports & Analytics (Financial)",
    subtitle: "Department and branch profitability reports",
    kpis: [
      { label: "Reports scheduled", value: "8", trend: "monthly", trendTone: "flat" },
      { label: "Gross margin", value: "57.4%", trend: "+1.2%", trendTone: "up" },
      { label: "Top department", value: "Pharmacy", trend: "₹6.2L", trendTone: "up" },
      { label: "Loss-making units", value: "1", trend: "Swimming", trendTone: "down" },
    ],
    seriesLabel: "Profit (₹ lakh)",
    series: series(8.1, 9.0, 9.4, 10.1, 10.4, 11.2),
    columns: [
      { key: "dept", label: "Department" },
      { key: "revenue", label: "Revenue", align: "right", kind: "money" },
      { key: "cost", label: "Cost", align: "right", kind: "money" },
      { key: "margin", label: "Margin" },
      { key: "status", label: "Trend", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { dept: "OPD", revenue: 640000, cost: 240000, margin: "62.5%", status: "Growing" },
      { dept: "Pharmacy", revenue: 620000, cost: 380000, margin: "38.7%", status: "Growing" },
      { dept: "Laboratory", revenue: 410000, cost: 150000, margin: "63.4%", status: "Stable" },
      { dept: "Boarding", revenue: 340000, cost: 190000, margin: "44.1%", status: "Stable" },
      { dept: "Swimming", revenue: 110000, cost: 128000, margin: "-16.4%", status: "Declining" },
    ],
    createLabel: "Add Department",
    fields: [
      { key: "dept", label: "Department", type: "text", required: true },
      { key: "revenue", label: "Revenue", type: "number", required: true },
      { key: "cost", label: "Cost", type: "number", required: true },
      { key: "margin", label: "Margin", type: "text", required: true },
      { key: "status", label: "Trend", type: "select", options: ["Growing", "Stable", "Declining"], required: true },
    ],
  },

  integrations: {
    id: "integrations",
    icon: "Plug",
    title: "Integration Hub & Settings (Branch)",
    subtitle: "Branch-level service catalogue and configuration",
    kpis: [
      { label: "Active integrations", value: "6", trend: "all healthy", trendTone: "up" },
      { label: "Service catalogue items", value: "84", trend: "+6", trendTone: "up" },
      { label: "Tax profiles", value: "3", trend: "GST 5/12/18", trendTone: "flat" },
      { label: "Printers configured", value: "4", trend: "2 counters", trendTone: "flat" },
    ],
    columns: [
      { key: "name", label: "Setting / Integration" },
      { key: "type", label: "Type" },
      { key: "value", label: "Configuration" },
      { key: "updated", label: "Updated" },
      { key: "status", label: "Status", kind: "status" },
    ],
    statusKey: "status",
    rows: [
      { name: "WhatsApp Business", type: "Messaging", value: "+91 90000 00000", updated: "2026-08-10", status: "Connected" },
      { name: "Razorpay POS", type: "Payments", value: "Terminal RZP-2291", updated: "2026-08-12", status: "Connected" },
      { name: "GST profile", type: "Compliance", value: "36AACCV1234K1ZP", updated: "2026-07-01", status: "Connected" },
      { name: "Thermal printer — Counter 2", type: "Hardware", value: "TSP-100 · USB", updated: "2026-08-14", status: "Connected" },
      { name: "Google Calendar sync", type: "Scheduling", value: "clinic@pawsclaws.in", updated: "2026-06-22", status: "Disabled" },
    ],
    createLabel: "Add Integration",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "type", label: "Type", type: "select", options: ["Messaging", "Payments", "Compliance", "Hardware", "Scheduling"], required: true },
      { key: "value", label: "Configuration", type: "text", required: true },
      { key: "updated", label: "Updated", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["Connected", "Disabled", "Failing"], required: true },
    ],
  },
};

export function getWorkspace(id: string): Workspace | undefined {
  return WORKSPACES[id];
}
