/**
 * Authoritative Seed Data for VetOS Inventory & Product Catalogue Redesign
 * Contains 52 items classified into 10 Medicines, 7 Food items, and 35 Accessories
 * backed by initial opening stock batches and ledger entries.
 */

export interface SeedMedicineDetail {
  medicineType: string;
  genericComposition: string;
  strength: string;
  dosageForm: string;
  packSize: string;
  batchNumber: string;
  expiryDate: string;
}

export interface SeedFoodDetail {
  foodType: string;
  species: string;
  variantFlavour: string;
  packSize: string;
}

export interface SeedAccessoryDetail {
  accessoryType: string;
  sizeVariant: string;
}

export interface SeedItem {
  itemCode: string;
  productType: "MEDICINE" | "FOOD" | "ACCESSORY";
  name: string;
  genericName: string;
  brand: string;
  manufacturer: string;
  description: string;
  category: "Medicine" | "Food" | "Accessory" | "Consumable" | "Animal Food" | "Animal Accessories";
  subGroup: string;
  hasVariants: boolean;
  sku: string;
  unit: "Tablet" | "ml" | "Vial" | "Box" | "Strip" | "Kg" | "Bottle" | "Unit" | "Piece" | "Gm" | "Litre";
  purchaseUom: string;
  salesUom: string;
  uomConversions: { uom: string; conversionFactor: number }[];
  maintainStock: boolean;
  valuationMethod: "FEFO" | "FIFO" | "Moving Average";
  currentStock: number;
  minStockLevel: number;
  reorderLevel: number;
  reorderQty: number;
  safetyStock: number;
  storageLocation: string;
  batchTracking: boolean;
  serialTracking: boolean;
  allowNegativeStock: boolean;
  defaultSalePrice: number;
  defaultPurchasePrice: number;
  mrp: number;
  minSalePrice: number;
  maxDiscountPct: number;
  valuationRate: number;
  lastPurchaseRate: number;
  gstRate: number;
  hsnCode: string;
  taxCategory: string;
  isZeroRated: boolean;
  isExempt: boolean;
  isImport: boolean;
  defaultSupplierId: string;
  defaultSupplierName: string;
  leadTimeDays: number;
  minOrderQty: number;
  purchaseAccount: string;
  expenseAccount: string;
  incomeAccount: string;
  costCenter: string;
  isSalesItem: boolean;
  allowAlternativeItem: boolean;
  status: "Active" | "Inactive";
  createdAt: string;
  samplePriceNote?: string;
  medicineDetails?: SeedMedicineDetail;
  foodDetails?: SeedFoodDetail;
  accessoryDetails?: SeedAccessoryDetail;
}

export type MedicineDetails = SeedMedicineDetail & {
  composition?: string;
  route?: string;
  storageCondition?: string;
  schedule?: string;
  controlledSubstance?: boolean;
};

export type FoodDetails = SeedFoodDetail & {
  targetSpecies?: string;
  lifeStage?: string;
  flavour?: string;
  dietaryIndication?: string;
};

export type AccessoryDetails = SeedAccessoryDetail & {
  petSize?: string;
  material?: string;
  color?: string;
};

// ─── 10 Medicines ─────────────────────────────────────────────────────────────
export const SEED_MEDICINES: SeedItem[] = [
  {
    itemCode: "M-0001",
    productType: "MEDICINE",
    name: "Amoxicillin 250mg",
    genericName: "Amoxicillin Trihydrate",
    brand: "Moxivet",
    manufacturer: "Cipla Animal Health",
    description: "Broad-spectrum bactericidal penicillin for respiratory & soft tissue infections",
    category: "Medicine",
    subGroup: "Antibiotics",
    hasVariants: false,
    sku: "MED-AMX-250",
    unit: "Tablet",
    purchaseUom: "Box",
    salesUom: "Tablet",
    uomConversions: [{ uom: "Box", conversionFactor: 100 }],
    maintainStock: true,
    valuationMethod: "FEFO",
    currentStock: 50,
    minStockLevel: 25,
    reorderLevel: 50,
    reorderQty: 100,
    safetyStock: 20,
    storageLocation: "Pharmacy Rack A1",
    batchTracking: true,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 24,
    defaultPurchasePrice: 16,
    mrp: 28,
    minSalePrice: 18,
    maxDiscountPct: 10,
    valuationRate: 16,
    lastPurchaseRate: 16,
    gstRate: 12,
    hsnCode: "30041000",
    taxCategory: "Pharma Standard",
    isZeroRated: false,
    isExempt: false,
    isImport: false,
    defaultSupplierId: "SUP-01",
    defaultSupplierName: "MedVet Distributors",
    leadTimeDays: 7,
    minOrderQty: 50,
    purchaseAccount: "5000 - Pharmacy Inventory",
    expenseAccount: "5200 - Cost of Goods Sold",
    incomeAccount: "4200 - Pharmacy Sales",
    costCenter: "Clinical Pharmacy",
    isSalesItem: true,
    allowAlternativeItem: true,
    status: "Active",
    createdAt: "2026-08-23",
    medicineDetails: {
      medicineType: "Antibiotic",
      genericComposition: "Amoxicillin Trihydrate IP 250mg",
      strength: "250mg",
      dosageForm: "Tablet",
      packSize: "Strip of 10 Tablets",
      batchNumber: "AMX-2025-01",
      expiryDate: "2027-08-30",
    },
  },
  {
    itemCode: "M-0002",
    productType: "MEDICINE",
    name: "Rabies Vaccine 1ml",
    genericName: "Inactivated Rabies glycoprotein virus",
    brand: "Nobivac R",
    manufacturer: "MSD Animal Health",
    description: "Inactivated cell-culture vaccine for prophylactic immunization against rabies in dogs & cats",
    category: "Medicine",
    subGroup: "Biologicals & Vaccines",
    hasVariants: false,
    sku: "MED-VAC-RAB",
    unit: "Vial",
    purchaseUom: "Box",
    salesUom: "Vial",
    uomConversions: [{ uom: "Box", conversionFactor: 10 }],
    maintainStock: true,
    valuationMethod: "FEFO",
    currentStock: 12,
    minStockLevel: 10,
    reorderLevel: 20,
    reorderQty: 30,
    safetyStock: 5,
    storageLocation: "Cold Storage Refrigerator 2-8°C",
    batchTracking: true,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 480,
    defaultPurchasePrice: 340,
    mrp: 520,
    minSalePrice: 380,
    maxDiscountPct: 5,
    valuationRate: 340,
    lastPurchaseRate: 340,
    gstRate: 5,
    hsnCode: "30022019",
    taxCategory: "Vaccine Reduced",
    isZeroRated: false,
    isExempt: false,
    isImport: false,
    defaultSupplierId: "SUP-02",
    defaultSupplierName: "BioPharm India",
    leadTimeDays: 14,
    minOrderQty: 10,
    purchaseAccount: "5000 - Pharmacy Inventory",
    expenseAccount: "5200 - Cost of Goods Sold",
    incomeAccount: "4200 - Pharmacy Sales",
    costCenter: "Vaccination Clinic",
    isSalesItem: true,
    allowAlternativeItem: false,
    status: "Active",
    createdAt: "2026-08-23",
    medicineDetails: {
      medicineType: "Vaccine",
      genericComposition: "Inactivated Rabies Virus Pasteur RIV strain >= 2.0 IU",
      strength: "1ml (1 Dose)",
      dosageForm: "Injectable Suspension",
      packSize: "Single Dose 1ml Vial",
      batchNumber: "RBV-2025-01",
      expiryDate: "2027-04-15",
    },
  },
  {
    itemCode: "M-0003",
    productType: "MEDICINE",
    name: "IV Fluid RL 500ml",
    genericName: "Compound Sodium Lactate / Ringer Lactate",
    brand: "RingerLac",
    manufacturer: "CareSupplies Healthcare",
    description: "Sterile intravenous infusion solution for fluid replenishment and electrolyte balance",
    category: "Medicine",
    subGroup: "Infusions & Fluids",
    hasVariants: false,
    sku: "MED-IVF-RL",
    unit: "Bottle",
    purchaseUom: "Carton",
    salesUom: "Bottle",
    uomConversions: [{ uom: "Carton", conversionFactor: 24 }],
    maintainStock: true,
    valuationMethod: "FEFO",
    currentStock: 6,
    minStockLevel: 15,
    reorderLevel: 30,
    reorderQty: 60,
    safetyStock: 10,
    storageLocation: "IV Fluid Bay B3",
    batchTracking: true,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 65,
    defaultPurchasePrice: 42,
    mrp: 75,
    minSalePrice: 50,
    maxDiscountPct: 10,
    valuationRate: 42,
    lastPurchaseRate: 42,
    gstRate: 5,
    hsnCode: "30049099",
    taxCategory: "Pharma Reduced",
    isZeroRated: false,
    isExempt: false,
    isImport: false,
    defaultSupplierId: "SUP-03",
    defaultSupplierName: "CareSupplies",
    leadTimeDays: 3,
    minOrderQty: 24,
    purchaseAccount: "5000 - Pharmacy Inventory",
    expenseAccount: "5200 - Cost of Goods Sold",
    incomeAccount: "4200 - Pharmacy Sales",
    costCenter: "ICU & Operation Theatre",
    isSalesItem: true,
    allowAlternativeItem: true,
    status: "Active",
    createdAt: "2026-08-23",
    medicineDetails: {
      medicineType: "IV Fluid",
      genericComposition: "Sodium Lactate 3.2g, NaCl 6.0g, KCl 0.4g, CaCl2 0.27g per litre",
      strength: "500ml",
      dosageForm: "Intravenous Infusion",
      packSize: "500ml Polyethylene Bottle",
      batchNumber: "IVF-2025-03",
      expiryDate: "2027-09-01",
    },
  },
  {
    itemCode: "M-0004",
    productType: "MEDICINE",
    name: "Dexamethasone 4mg",
    genericName: "Dexamethasone Sodium Phosphate",
    brand: "Dexona Vet",
    manufacturer: "BioPharm India",
    description: "Potent anti-inflammatory corticosteroid for acute allergies, shock & anaphylaxis",
    category: "Medicine",
    subGroup: "Corticosteroids",
    hasVariants: false,
    sku: "MED-DEX-4MG",
    unit: "Vial",
    purchaseUom: "Box",
    salesUom: "Vial",
    uomConversions: [{ uom: "Box", conversionFactor: 25 }],
    maintainStock: true,
    valuationMethod: "FEFO",
    currentStock: 28,
    minStockLevel: 10,
    reorderLevel: 15,
    reorderQty: 30,
    safetyStock: 5,
    storageLocation: "Pharmacy Locked Cabinet C",
    batchTracking: true,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 95,
    defaultPurchasePrice: 68,
    mrp: 110,
    minSalePrice: 75,
    maxDiscountPct: 10,
    valuationRate: 68,
    lastPurchaseRate: 68,
    gstRate: 12,
    hsnCode: "30043200",
    taxCategory: "Pharma Standard",
    isZeroRated: false,
    isExempt: false,
    isImport: false,
    defaultSupplierId: "SUP-02",
    defaultSupplierName: "BioPharm India",
    leadTimeDays: 7,
    minOrderQty: 10,
    purchaseAccount: "5000 - Pharmacy Inventory",
    expenseAccount: "5200 - Cost of Goods Sold",
    incomeAccount: "4200 - Pharmacy Sales",
    costCenter: "Emergency Care",
    isSalesItem: true,
    allowAlternativeItem: false,
    status: "Active",
    createdAt: "2026-08-23",
    medicineDetails: {
      medicineType: "Steroid",
      genericComposition: "Dexamethasone Sodium Phosphate 4mg/ml",
      strength: "4mg/ml",
      dosageForm: "Injectable Solution",
      packSize: "2ml Glass Vial",
      batchNumber: "DEX-2025-01",
      expiryDate: "2027-11-30",
    },
  },
  {
    itemCode: "M-0005",
    productType: "MEDICINE",
    name: "Deworming Syrup 30ml",
    genericName: "Pyrantel Pamoate & Febantel",
    brand: "WormTrap",
    manufacturer: "BioPharm India",
    description: "Oral anthelmintic suspension targeting ascarids, hookworms, and whipworms in puppies & kittens",
    category: "Medicine",
    subGroup: "Anthelmintics",
    hasVariants: false,
    sku: "MED-DWS-30ML",
    unit: "Bottle",
    purchaseUom: "Box",
    salesUom: "Bottle",
    uomConversions: [{ uom: "Box", conversionFactor: 20 }],
    maintainStock: true,
    valuationMethod: "FEFO",
    currentStock: 25,
    minStockLevel: 10,
    reorderLevel: 20,
    reorderQty: 40,
    safetyStock: 5,
    storageLocation: "Pharmacy Rack B2",
    batchTracking: true,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 95,
    defaultPurchasePrice: 62,
    mrp: 120,
    minSalePrice: 75,
    maxDiscountPct: 10,
    valuationRate: 62,
    lastPurchaseRate: 62,
    gstRate: 12,
    hsnCode: "30049099",
    taxCategory: "Pharma Standard",
    isZeroRated: false,
    isExempt: false,
    isImport: false,
    defaultSupplierId: "SUP-02",
    defaultSupplierName: "BioPharm India",
    leadTimeDays: 7,
    minOrderQty: 12,
    purchaseAccount: "5000 - Pharmacy Inventory",
    expenseAccount: "5200 - Cost of Goods Sold",
    incomeAccount: "4200 - Pharmacy Sales",
    costCenter: "Clinical Pharmacy",
    isSalesItem: true,
    allowAlternativeItem: true,
    status: "Active",
    createdAt: "2026-08-23",
    medicineDetails: {
      medicineType: "Anthelmintic",
      genericComposition: "Pyrantel Pamoate 14.4mg + Febantel 15mg per ml",
      strength: "30ml",
      dosageForm: "Oral Suspension",
      packSize: "30ml Amber Pet Bottle with Calibrated Dropper",
      batchNumber: "DWS-2025-04",
      expiryDate: "2027-05-15",
    },
  },
  {
    itemCode: "M-0006",
    productType: "MEDICINE",
    name: "IV Catheter 20G",
    genericName: "Peripheral Intravenous Cannula 20G",
    brand: "VeinFlo Vet",
    manufacturer: "CareSupplies Healthcare",
    description: "Sterile non-pyrogenic IV cannula with injection port and radiopaque stripes",
    category: "Medicine",
    subGroup: "Consumables & Disposables",
    hasVariants: false,
    sku: "MED-IVC-20G",
    unit: "Box",
    purchaseUom: "Carton",
    salesUom: "Box",
    uomConversions: [{ uom: "Carton", conversionFactor: 10 }],
    maintainStock: true,
    valuationMethod: "FIFO",
    currentStock: 0,
    minStockLevel: 20,
    reorderLevel: 40,
    reorderQty: 100,
    safetyStock: 10,
    storageLocation: "Consumables Cabinet 1",
    batchTracking: false,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 45,
    defaultPurchasePrice: 30,
    mrp: 60,
    minSalePrice: 35,
    maxDiscountPct: 10,
    valuationRate: 30,
    lastPurchaseRate: 30,
    gstRate: 12,
    hsnCode: "90183900",
    taxCategory: "Medical Devices",
    isZeroRated: false,
    isExempt: false,
    isImport: false,
    defaultSupplierId: "SUP-03",
    defaultSupplierName: "CareSupplies",
    leadTimeDays: 5,
    minOrderQty: 20,
    purchaseAccount: "5000 - Pharmacy Inventory",
    expenseAccount: "5200 - Cost of Goods Sold",
    incomeAccount: "4200 - Pharmacy Sales",
    costCenter: "ICU & Operation Theatre",
    isSalesItem: true,
    allowAlternativeItem: false,
    status: "Active",
    createdAt: "2026-08-23",
    medicineDetails: {
      medicineType: "Medical Device / Consumable",
      genericComposition: "PTFE Cannula with stainless steel introducer needle",
      strength: "20 Gauge x 32mm (Pink)",
      dosageForm: "Sterile Device",
      packSize: "Box of 50 Individually Blister-Packed Units",
      batchNumber: "IVC-2025-02",
      expiryDate: "2028-06-30",
    },
  },
  {
    itemCode: "M-0007",
    productType: "MEDICINE",
    name: "Metronidazole 200mg",
    genericName: "Metronidazole IP",
    brand: "Metrogyl Vet",
    manufacturer: "MedVet Distributors",
    description: "Antiprotozoal & anaerobic antibacterial agent for giardiasis, trichomoniasis & bowel infections",
    category: "Medicine",
    subGroup: "Antiprotozoals",
    hasVariants: false,
    sku: "MED-MTZ-200",
    unit: "Tablet",
    purchaseUom: "Box",
    salesUom: "Tablet",
    uomConversions: [{ uom: "Box", conversionFactor: 100 }],
    maintainStock: true,
    valuationMethod: "FEFO",
    currentStock: 220,
    minStockLevel: 50,
    reorderLevel: 100,
    reorderQty: 200,
    safetyStock: 30,
    storageLocation: "Pharmacy Rack A2",
    batchTracking: true,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 8,
    defaultPurchasePrice: 5,
    mrp: 10,
    minSalePrice: 6,
    maxDiscountPct: 10,
    valuationRate: 5,
    lastPurchaseRate: 5,
    gstRate: 12,
    hsnCode: "30049099",
    taxCategory: "Pharma Standard",
    isZeroRated: false,
    isExempt: false,
    isImport: false,
    defaultSupplierId: "SUP-01",
    defaultSupplierName: "MedVet Distributors",
    leadTimeDays: 7,
    minOrderQty: 100,
    purchaseAccount: "5000 - Pharmacy Inventory",
    expenseAccount: "5200 - Cost of Goods Sold",
    incomeAccount: "4200 - Pharmacy Sales",
    costCenter: "Clinical Pharmacy",
    isSalesItem: true,
    allowAlternativeItem: true,
    status: "Active",
    createdAt: "2026-08-23",
    medicineDetails: {
      medicineType: "Antiprotozoal / Antibacterial",
      genericComposition: "Metronidazole IP 200mg",
      strength: "200mg",
      dosageForm: "Tablet",
      packSize: "Strip of 10 Tablets",
      batchNumber: "MTZ-2025-01",
      expiryDate: "2027-10-31",
    },
  },
  {
    itemCode: "M-0008",
    productType: "MEDICINE",
    name: "Canishot DHPPiL",
    genericName: "Canine Distemper, Hepatitis, Parvovirus, Parainfluenza & Leptospirosis Vaccine",
    brand: "Canishot",
    manufacturer: "MSD Animal Health",
    description: "Core 9-in-1 multivalent vaccine providing active immunization against principal canine infectious diseases",
    category: "Medicine",
    subGroup: "Biologicals & Vaccines",
    hasVariants: false,
    sku: "MED-VAC-DHPPIL",
    unit: "Vial",
    purchaseUom: "Box",
    salesUom: "Vial",
    uomConversions: [{ uom: "Box", conversionFactor: 25 }],
    maintainStock: true,
    valuationMethod: "FEFO",
    currentStock: 18,
    minStockLevel: 10,
    reorderLevel: 25,
    reorderQty: 50,
    safetyStock: 8,
    storageLocation: "Cold Storage Refrigerator 2-8°C",
    batchTracking: true,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 1350,
    defaultPurchasePrice: 950,
    mrp: 1500,
    minSalePrice: 1100,
    maxDiscountPct: 5,
    valuationRate: 950,
    lastPurchaseRate: 950,
    gstRate: 5,
    hsnCode: "30022019",
    taxCategory: "Vaccine Reduced",
    isZeroRated: false,
    isExempt: false,
    isImport: false,
    defaultSupplierId: "SUP-02",
    defaultSupplierName: "BioPharm India",
    leadTimeDays: 10,
    minOrderQty: 10,
    purchaseAccount: "5000 - Pharmacy Inventory",
    expenseAccount: "5200 - Cost of Goods Sold",
    incomeAccount: "4200 - Pharmacy Sales",
    costCenter: "Vaccination Clinic",
    isSalesItem: true,
    allowAlternativeItem: false,
    status: "Active",
    createdAt: "2026-08-23",
    medicineDetails: {
      medicineType: "Vaccine",
      genericComposition: "Live attenuated CDV, CAV-2, CPV, CPiV with inactivated Leptospira canicola & icterohaemorrhagiae",
      strength: "1 Dose (Lyophilized cake + diluent)",
      dosageForm: "Injectable Suspension",
      packSize: "Dual Vial Pack (Antigen + Diluent)",
      batchNumber: "CSH-2025-08",
      expiryDate: "2027-02-28",
    },
  },
  {
    itemCode: "M-0009",
    productType: "MEDICINE",
    name: "Meloxicam Oral Suspension 10ml",
    genericName: "Meloxicam IP",
    brand: "Melonex",
    manufacturer: "Intas Pharmaceuticals",
    description: "Preferential COX-2 inhibitor non-steroidal anti-inflammatory for acute and chronic musculoskeletal pain",
    category: "Medicine",
    subGroup: "NSAIDs & Analgesics",
    hasVariants: false,
    sku: "MED-MEL-10ML",
    unit: "Bottle",
    purchaseUom: "Box",
    salesUom: "Bottle",
    uomConversions: [{ uom: "Box", conversionFactor: 12 }],
    maintainStock: true,
    valuationMethod: "FEFO",
    currentStock: 34,
    minStockLevel: 12,
    reorderLevel: 20,
    reorderQty: 40,
    safetyStock: 6,
    storageLocation: "Pharmacy Rack B1",
    batchTracking: true,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 145,
    defaultPurchasePrice: 98,
    mrp: 165,
    minSalePrice: 120,
    maxDiscountPct: 10,
    valuationRate: 98,
    lastPurchaseRate: 98,
    gstRate: 12,
    hsnCode: "30049099",
    taxCategory: "Pharma Standard",
    isZeroRated: false,
    isExempt: false,
    isImport: false,
    defaultSupplierId: "SUP-01",
    defaultSupplierName: "MedVet Distributors",
    leadTimeDays: 7,
    minOrderQty: 10,
    purchaseAccount: "5000 - Pharmacy Inventory",
    expenseAccount: "5200 - Cost of Goods Sold",
    incomeAccount: "4200 - Pharmacy Sales",
    costCenter: "Clinical Pharmacy",
    isSalesItem: true,
    allowAlternativeItem: true,
    status: "Active",
    createdAt: "2026-08-23",
    medicineDetails: {
      medicineType: "NSAID",
      genericComposition: "Meloxicam IP 1.5mg/ml oral suspension",
      strength: "1.5mg/ml",
      dosageForm: "Oral Suspension",
      packSize: "10ml Bottle with dosing syringe",
      batchNumber: "MLX-2025-03",
      expiryDate: "2027-12-31",
    },
  },
  {
    itemCode: "M-0010",
    productType: "MEDICINE",
    name: "Ceftriaxone 1g Injection",
    genericName: "Ceftriaxone Sodium Sterile IP",
    brand: "Intacef Tazo",
    manufacturer: "Zydus Animal Health",
    description: "Third-generation cephalosporin antibiotic with beta-lactamase inhibitor for severe multi-system bacterial infections",
    category: "Medicine",
    subGroup: "Antibiotics",
    hasVariants: false,
    sku: "MED-CEF-1G",
    unit: "Vial",
    purchaseUom: "Box",
    salesUom: "Vial",
    uomConversions: [{ uom: "Box", conversionFactor: 10 }],
    maintainStock: true,
    valuationMethod: "FEFO",
    currentStock: 16,
    minStockLevel: 8,
    reorderLevel: 15,
    reorderQty: 30,
    safetyStock: 4,
    storageLocation: "Pharmacy Rack A1",
    batchTracking: true,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 180,
    defaultPurchasePrice: 125,
    mrp: 210,
    minSalePrice: 150,
    maxDiscountPct: 10,
    valuationRate: 125,
    lastPurchaseRate: 125,
    gstRate: 12,
    hsnCode: "30042099",
    taxCategory: "Pharma Standard",
    isZeroRated: false,
    isExempt: false,
    isImport: false,
    defaultSupplierId: "SUP-01",
    defaultSupplierName: "MedVet Distributors",
    leadTimeDays: 7,
    minOrderQty: 10,
    purchaseAccount: "5000 - Pharmacy Inventory",
    expenseAccount: "5200 - Cost of Goods Sold",
    incomeAccount: "4200 - Pharmacy Sales",
    costCenter: "Surgery & Inpatient",
    isSalesItem: true,
    allowAlternativeItem: false,
    status: "Active",
    createdAt: "2026-08-23",
    medicineDetails: {
      medicineType: "Antibiotic",
      genericComposition: "Ceftriaxone Sodium IP 1000mg + Sterile Water for Injection",
      strength: "1000mg (1g)",
      dosageForm: "Dry Powder for Injection with Diluent",
      packSize: "Glass Vial + 10ml Sterile Water Ampoule",
      batchNumber: "CFT-2025-06",
      expiryDate: "2027-06-30",
    },
  },
];

// ─── 7 Food Items ─────────────────────────────────────────────────────────────
export const SEED_FOOD: SeedItem[] = [
  {
    itemCode: "F-0001",
    productType: "FOOD",
    name: "Royal Canin Maxi Adult 4kg",
    genericName: "Canine adult large breed maintenance diet",
    brand: "Royal Canin",
    manufacturer: "Royal Canin SAS France",
    description: "Complete nutrition specifically formulated for large breed adult dogs (26-44kg) over 15 months of age",
    category: "Animal Food",
    subGroup: "Dry Dog Food",
    hasVariants: false,
    sku: "FOOD-RC-MAXI-4K",
    unit: "Box",
    purchaseUom: "Bag",
    salesUom: "Bag",
    uomConversions: [{ uom: "Bag", conversionFactor: 1 }],
    maintainStock: true,
    valuationMethod: "FEFO",
    currentStock: 24,
    minStockLevel: 5,
    reorderLevel: 8,
    reorderQty: 20,
    safetyStock: 3,
    storageLocation: "Retail Shelf D1",
    batchTracking: true,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 1850,
    defaultPurchasePrice: 1400,
    mrp: 2050,
    minSalePrice: 1600,
    maxDiscountPct: 5,
    valuationRate: 1400,
    lastPurchaseRate: 1400,
    gstRate: 5,
    hsnCode: "23091000",
    taxCategory: "Pet Nutrition Reduced",
    isZeroRated: false,
    isExempt: false,
    isImport: true,
    defaultSupplierId: "SUP-04",
    defaultSupplierName: "PetNutri India",
    leadTimeDays: 7,
    minOrderQty: 5,
    purchaseAccount: "5010 - Food & Retail Inventory",
    expenseAccount: "5210 - Cost of Retail Goods",
    incomeAccount: "4210 - Nutrition & Retail Sales",
    costCenter: "Retail Pharmacy",
    isSalesItem: true,
    allowAlternativeItem: true,
    status: "Active",
    createdAt: "2025-08-01",
    foodDetails: {
      foodType: "Dry Kibble",
      species: "Canine (Large Breed)",
      variantFlavour: "Poultry & Rice with Joint Complex",
      packSize: "4kg Bag",
    },
  },
  {
    itemCode: "F-0002",
    productType: "FOOD",
    name: "Pedigree Adult Chicken & Vegetables 3kg",
    genericName: "Complete dry dog food with real chicken",
    brand: "Pedigree",
    manufacturer: "Mars Petcare India",
    description: "100% complete adult dog food with wholesome chicken and vegetables for balanced everyday nutrition",
    category: "Animal Food",
    subGroup: "Dry Dog Food",
    hasVariants: false,
    sku: "FOOD-PED-CHK-3K",
    unit: "Box",
    purchaseUom: "Bag",
    salesUom: "Bag",
    uomConversions: [{ uom: "Bag", conversionFactor: 1 }],
    maintainStock: true,
    valuationMethod: "FEFO",
    currentStock: 30,
    minStockLevel: 6,
    reorderLevel: 10,
    reorderQty: 25,
    safetyStock: 4,
    storageLocation: "Retail Shelf D1",
    batchTracking: true,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 890,
    defaultPurchasePrice: 680,
    mrp: 950,
    minSalePrice: 750,
    maxDiscountPct: 5,
    valuationRate: 680,
    lastPurchaseRate: 680,
    gstRate: 5,
    hsnCode: "23091000",
    taxCategory: "Pet Nutrition Reduced",
    isZeroRated: false,
    isExempt: false,
    isImport: false,
    defaultSupplierId: "SUP-04",
    defaultSupplierName: "PetNutri India",
    leadTimeDays: 5,
    minOrderQty: 10,
    purchaseAccount: "5010 - Food & Retail Inventory",
    expenseAccount: "5210 - Cost of Retail Goods",
    incomeAccount: "4210 - Nutrition & Retail Sales",
    costCenter: "Retail Pharmacy",
    isSalesItem: true,
    allowAlternativeItem: true,
    status: "Active",
    createdAt: "2025-07-15",
    foodDetails: {
      foodType: "Dry Kibble",
      species: "Canine (All Breeds)",
      variantFlavour: "Chicken & Vegetables",
      packSize: "3kg Bag",
    },
  },
  {
    itemCode: "F-0003",
    productType: "FOOD",
    name: "Hill's Science Diet Kitten 1.58kg",
    genericName: "Scientifically formulated kitten development diet",
    brand: "Hill's",
    manufacturer: "Hill's Pet Nutrition USA",
    description: "Premium dry cat food with natural DHA from fish oil to support brain & eye development in kittens",
    category: "Animal Food",
    subGroup: "Dry Cat Food",
    hasVariants: false,
    sku: "FOOD-HSD-KIT-1.58K",
    unit: "Box",
    purchaseUom: "Bag",
    salesUom: "Bag",
    uomConversions: [{ uom: "Bag", conversionFactor: 1 }],
    maintainStock: true,
    valuationMethod: "FEFO",
    currentStock: 20,
    minStockLevel: 4,
    reorderLevel: 6,
    reorderQty: 15,
    safetyStock: 2,
    storageLocation: "Retail Shelf D2",
    batchTracking: true,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 2400,
    defaultPurchasePrice: 1850,
    mrp: 2650,
    minSalePrice: 2100,
    maxDiscountPct: 5,
    valuationRate: 1850,
    lastPurchaseRate: 1850,
    gstRate: 5,
    hsnCode: "23091000",
    taxCategory: "Pet Nutrition Reduced",
    isZeroRated: false,
    isExempt: false,
    isImport: true,
    defaultSupplierId: "SUP-04",
    defaultSupplierName: "PetNutri India",
    leadTimeDays: 10,
    minOrderQty: 3,
    purchaseAccount: "5010 - Food & Retail Inventory",
    expenseAccount: "5210 - Cost of Retail Goods",
    incomeAccount: "4210 - Nutrition & Retail Sales",
    costCenter: "Retail Pharmacy",
    isSalesItem: true,
    allowAlternativeItem: false,
    status: "Active",
    createdAt: "2025-08-10",
    foodDetails: {
      foodType: "Dry Kibble",
      species: "Feline (Kittens & Nursing Queens)",
      variantFlavour: "Ocean Fish & Brown Rice",
      packSize: "1.58kg Bag",
    },
  },
  {
    itemCode: "F-0004",
    productType: "FOOD",
    name: "Whiskas Ocean Fish Adult 1.2kg",
    genericName: "Complete adult cat dry food with real ocean fish",
    brand: "Whiskas",
    manufacturer: "Mars Petcare India",
    description: "Crunchy pockets packed with essential nutrients, zinc & taurine for vibrant coat and clear feline eyesight",
    category: "Animal Food",
    subGroup: "Dry Cat Food",
    hasVariants: false,
    sku: "FOOD-WHK-FISH-1.2K",
    unit: "Box",
    purchaseUom: "Bag",
    salesUom: "Bag",
    uomConversions: [{ uom: "Bag", conversionFactor: 1 }],
    maintainStock: true,
    valuationMethod: "FEFO",
    currentStock: 36,
    minStockLevel: 8,
    reorderLevel: 12,
    reorderQty: 30,
    safetyStock: 5,
    storageLocation: "Retail Shelf D2",
    batchTracking: true,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 650,
    defaultPurchasePrice: 480,
    mrp: 720,
    minSalePrice: 550,
    maxDiscountPct: 5,
    valuationRate: 480,
    lastPurchaseRate: 480,
    gstRate: 5,
    hsnCode: "23091000",
    taxCategory: "Pet Nutrition Reduced",
    isZeroRated: false,
    isExempt: false,
    isImport: false,
    defaultSupplierId: "SUP-04",
    defaultSupplierName: "PetNutri India",
    leadTimeDays: 5,
    minOrderQty: 12,
    purchaseAccount: "5010 - Food & Retail Inventory",
    expenseAccount: "5210 - Cost of Retail Goods",
    incomeAccount: "4210 - Nutrition & Retail Sales",
    costCenter: "Retail Pharmacy",
    isSalesItem: true,
    allowAlternativeItem: true,
    status: "Active",
    createdAt: "2025-07-20",
    foodDetails: {
      foodType: "Dry Kibble",
      species: "Feline (Adult Cats)",
      variantFlavour: "Ocean Fish with Salmon Pockets",
      packSize: "1.2kg Bag",
    },
  },
  {
    itemCode: "F-0005",
    productType: "FOOD",
    name: "Farmina Vet Life Gastrointestinal Wet Cat 85g",
    genericName: "Veterinary clinical diet for acute intestinal absorptive disorders",
    brand: "Farmina",
    manufacturer: "Farmina Pet Foods Italy",
    description: "Highly digestible therapeutic feline wet diet with increased sodium and potassium for gastrointestinal recovery (Brand verified for clinic launch)",
    category: "Animal Food",
    subGroup: "Veterinary Prescription Wet Diet",
    hasVariants: false,
    sku: "FOOD-FAR-GI-CAT-85G",
    unit: "Unit",
    purchaseUom: "Can",
    salesUom: "Can",
    uomConversions: [{ uom: "Tray", conversionFactor: 12 }],
    maintainStock: true,
    valuationMethod: "FEFO",
    currentStock: 48,
    minStockLevel: 12,
    reorderLevel: 24,
    reorderQty: 48,
    safetyStock: 8,
    storageLocation: "Clinical Diet Display C2",
    batchTracking: true,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 195,
    defaultPurchasePrice: 142,
    mrp: 220,
    minSalePrice: 170,
    maxDiscountPct: 5,
    valuationRate: 142,
    lastPurchaseRate: 142,
    gstRate: 5,
    hsnCode: "23091000",
    taxCategory: "Therapeutic Pet Diet",
    isZeroRated: false,
    isExempt: false,
    isImport: true,
    defaultSupplierId: "SUP-04",
    defaultSupplierName: "PetNutri India",
    leadTimeDays: 7,
    minOrderQty: 12,
    purchaseAccount: "5010 - Food & Retail Inventory",
    expenseAccount: "5210 - Cost of Retail Goods",
    incomeAccount: "4210 - Nutrition & Retail Sales",
    costCenter: "Veterinary Dietetics",
    isSalesItem: true,
    allowAlternativeItem: false,
    status: "Active",
    createdAt: "2025-08-15",
    foodDetails: {
      foodType: "Wet Gravy / Canned Loaf",
      species: "Feline (Therapeutic Recovery)",
      variantFlavour: "Digestive Care Chicken & Hydrolyzed Fish",
      packSize: "85g Can",
    },
  },
  {
    itemCode: "F-0006",
    productType: "FOOD",
    name: "Drools Focus Adult Super Premium 4kg",
    genericName: "Super premium breed-specific dog food with 100% natural ingredients",
    brand: "Drools",
    manufacturer: "Drools Pet Food India",
    description: "High protein real chicken food with no corn, wheat or soy, enriched with omega 3 & 6 for canine vitality",
    category: "Animal Food",
    subGroup: "Dry Dog Food",
    hasVariants: false,
    sku: "FOOD-DRO-FOC-4K",
    unit: "Box",
    purchaseUom: "Bag",
    salesUom: "Bag",
    uomConversions: [{ uom: "Bag", conversionFactor: 1 }],
    maintainStock: true,
    valuationMethod: "FEFO",
    currentStock: 18,
    minStockLevel: 5,
    reorderLevel: 8,
    reorderQty: 20,
    safetyStock: 3,
    storageLocation: "Retail Shelf D1",
    batchTracking: true,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 1750,
    defaultPurchasePrice: 1280,
    mrp: 1950,
    minSalePrice: 1500,
    maxDiscountPct: 5,
    valuationRate: 1280,
    lastPurchaseRate: 1280,
    gstRate: 5,
    hsnCode: "23091000",
    taxCategory: "Pet Nutrition Reduced",
    isZeroRated: false,
    isExempt: false,
    isImport: false,
    defaultSupplierId: "SUP-04",
    defaultSupplierName: "PetNutri India",
    leadTimeDays: 5,
    minOrderQty: 4,
    purchaseAccount: "5010 - Food & Retail Inventory",
    expenseAccount: "5210 - Cost of Retail Goods",
    incomeAccount: "4210 - Nutrition & Retail Sales",
    costCenter: "Retail Pharmacy",
    isSalesItem: true,
    allowAlternativeItem: true,
    status: "Active",
    createdAt: "2025-08-05",
    foodDetails: {
      foodType: "Dry Kibble",
      species: "Canine (All Adult Breeds)",
      variantFlavour: "Real Chicken, Egg & Rice",
      packSize: "4kg Bag",
    },
  },
  {
    itemCode: "F-0007",
    productType: "FOOD",
    name: "Royal Canin Recovery Wet Dog & Cat 195g",
    genericName: "High energy veterinary convalescence clinical diet",
    brand: "Royal Canin",
    manufacturer: "Royal Canin SAS France",
    description: "High energy density diet with smooth texture suitable for syringe or tube feeding during critical illness & post-surgery convalescence",
    category: "Animal Food",
    subGroup: "Clinical Recovery Diet",
    hasVariants: false,
    sku: "FOOD-RC-REC-195G",
    unit: "Unit",
    purchaseUom: "Can",
    salesUom: "Can",
    uomConversions: [{ uom: "Tray", conversionFactor: 12 }],
    maintainStock: true,
    valuationMethod: "FEFO",
    currentStock: 42,
    minStockLevel: 10,
    reorderLevel: 20,
    reorderQty: 36,
    safetyStock: 6,
    storageLocation: "ICU Clinical Pantry",
    batchTracking: true,
    serialTracking: false,
    allowNegativeStock: false,
    defaultSalePrice: 380,
    defaultPurchasePrice: 285,
    mrp: 420,
    minSalePrice: 320,
    maxDiscountPct: 5,
    valuationRate: 285,
    lastPurchaseRate: 285,
    gstRate: 5,
    hsnCode: "23091000",
    taxCategory: "Therapeutic Pet Diet",
    isZeroRated: false,
    isExempt: false,
    isImport: true,
    defaultSupplierId: "SUP-04",
    defaultSupplierName: "PetNutri India",
    leadTimeDays: 7,
    minOrderQty: 12,
    purchaseAccount: "5010 - Food & Retail Inventory",
    expenseAccount: "5210 - Cost of Retail Goods",
    incomeAccount: "4210 - Nutrition & Retail Sales",
    costCenter: "ICU & Inpatient Care",
    isSalesItem: true,
    allowAlternativeItem: false,
    status: "Active",
    createdAt: "2025-08-20",
    foodDetails: {
      foodType: "Wet Loaf",
      species: "Canine & Feline (Convalescent)",
      variantFlavour: "High-Energy Recovery Mousse",
      packSize: "195g Can",
    },
  },
];

// ─── 35 Accessories ───────────────────────────────────────────────────────────
export const SEED_ACCESSORIES: SeedItem[] = [
  { itemCode: "A-0001", name: "Ergonomic Padded Dog Harness (L)", brand: "PawShield", subGroup: "Apparel & Harness", unit: "Piece", currentStock: 15, salePrice: 1250, purchasePrice: 750, size: "Large", accType: "Harnesses & Gear" },
  { itemCode: "A-0002", name: "Ergonomic Padded Dog Harness (M)", brand: "PawShield", subGroup: "Apparel & Harness", unit: "Piece", currentStock: 18, salePrice: 1150, purchasePrice: 700, size: "Medium", accType: "Harnesses & Gear" },
  { itemCode: "A-0003", name: "Ergonomic Padded Dog Harness (S)", brand: "PawShield", subGroup: "Apparel & Harness", unit: "Piece", currentStock: 12, salePrice: 990, purchasePrice: 620, size: "Small", accType: "Harnesses & Gear" },
  { itemCode: "A-0004", name: "Nylon Training Leash 6ft (Reflective)", brand: "PawShield", subGroup: "Collars & Leashes", unit: "Piece", currentStock: 25, salePrice: 450, purchasePrice: 220, size: "6 Feet", accType: "Collars & Leashes" },
  { itemCode: "A-0005", name: "Retractable Dog Leash 5m Heavy Duty", brand: "PetCare Gear", subGroup: "Collars & Leashes", unit: "Piece", currentStock: 14, salePrice: 850, purchasePrice: 490, size: "5 Metres (Up to 35kg)", accType: "Collars & Leashes" },
  { itemCode: "A-0006", name: "Adjustable Nylon Dog Collar (L, Red)", brand: "PawShield", subGroup: "Collars & Leashes", unit: "Piece", currentStock: 20, salePrice: 320, purchasePrice: 160, size: "Large (18-26 inch)", accType: "Collars & Leashes" },
  { itemCode: "A-0007", name: "Adjustable Nylon Dog Collar (M, Blue)", brand: "PawShield", subGroup: "Collars & Leashes", unit: "Piece", currentStock: 22, salePrice: 280, purchasePrice: 140, size: "Medium (14-20 inch)", accType: "Collars & Leashes" },
  { itemCode: "A-0008", name: "Feline Breakaway Velvet Bell Collar", brand: "KittyChic", subGroup: "Collars & Leashes", unit: "Piece", currentStock: 30, salePrice: 220, purchasePrice: 95, size: "Universal Cat (8-12 inch)", accType: "Collars & Leashes" },
  { itemCode: "A-0009", name: "Orthopedic Memory Foam Pet Bed (XL)", brand: "ComfyPaws", subGroup: "Beds & Mats", unit: "Piece", currentStock: 8, salePrice: 3200, purchasePrice: 1900, size: "XL (110x85x15cm)", accType: "Beds & Mats" },
  { itemCode: "A-0010", name: "Orthopedic Memory Foam Pet Bed (L)", brand: "ComfyPaws", subGroup: "Beds & Mats", unit: "Piece", currentStock: 10, salePrice: 2600, purchasePrice: 1550, size: "Large (90x70x12cm)", accType: "Beds & Mats" },
  { itemCode: "A-0011", name: "Donut Cuddler Calming Cat Bed (M)", brand: "SleepWell Pets", subGroup: "Beds & Mats", unit: "Piece", currentStock: 16, salePrice: 1200, purchasePrice: 680, size: "Medium (50cm Dia)", accType: "Beds & Mats" },
  { itemCode: "A-0012", name: "Waterproof Pet Cooling Gel Mat (L)", brand: "ChillPaws", subGroup: "Beds & Mats", unit: "Piece", currentStock: 12, salePrice: 950, purchasePrice: 520, size: "Large (90x50cm)", accType: "Beds & Mats" },
  { itemCode: "A-0013", name: "Stainless Steel Anti-Skid Feeding Bowl (800ml)", brand: "DinePaws", subGroup: "Bowls & Feeders", unit: "Unit", currentStock: 20, salePrice: 650, purchasePrice: 350, size: "800ml (Large)", accType: "Bowls & Feeders" },
  { itemCode: "A-0014", name: "Stainless Steel Anti-Skid Feeding Bowl (400ml)", brand: "DinePaws", subGroup: "Bowls & Feeders", unit: "Unit", currentStock: 25, salePrice: 420, purchasePrice: 220, size: "400ml (Small/Medium)", accType: "Bowls & Feeders" },
  { itemCode: "A-0015", name: "Elevated Double Wooden Bowl Stand (M)", brand: "DinePaws", subGroup: "Bowls & Feeders", unit: "Set", currentStock: 10, salePrice: 1450, purchasePrice: 850, size: "Medium Elevated (2x450ml)", accType: "Bowls & Feeders" },
  { itemCode: "A-0016", name: "Automatic Pet Water Fountain 2.5L", brand: "PetHydro", subGroup: "Bowls & Feeders", unit: "Unit", currentStock: 8, salePrice: 1850, purchasePrice: 1100, size: "2.5 Litre Capacity", accType: "Bowls & Feeders" },
  { itemCode: "A-0017", name: "Hooded Feline Litter Box (Anti-Odour)", brand: "PurrClean", subGroup: "Litter & Waste", unit: "Unit", currentStock: 10, salePrice: 1850, purchasePrice: 1100, size: "Enclosed with Filter (55x40x42cm)", accType: "Litter & Waste" },
  { itemCode: "A-0018", name: "Open High-Rim Feline Litter Tray (L)", brand: "PurrClean", subGroup: "Litter & Waste", unit: "Unit", currentStock: 15, salePrice: 850, purchasePrice: 480, size: "Large High Rim (50x38x20cm)", accType: "Litter & Waste" },
  { itemCode: "A-0019", name: "Heavy-Duty Cat Litter Scoop", brand: "PurrClean", subGroup: "Litter & Waste", unit: "Piece", currentStock: 40, salePrice: 180, purchasePrice: 70, size: "Standard Slotted", accType: "Litter & Waste" },
  { itemCode: "A-0020", name: "Biodegradable Dog Poop Bags (8 Rolls / 120 Bags)", brand: "EcoPaws", subGroup: "Litter & Waste", unit: "Box", currentStock: 35, salePrice: 350, purchasePrice: 180, size: "8 Rolls (120 Bags + Dispenser)", accType: "Litter & Waste" },
  { itemCode: "A-0021", name: "Self-Cleaning Slicker Brush for Dogs/Cats", brand: "GroomEase", subGroup: "Grooming & Hygiene", unit: "Piece", currentStock: 22, salePrice: 550, purchasePrice: 280, size: "Universal Retractable", accType: "Grooming & Hygiene" },
  { itemCode: "A-0022", name: "Double-Sided Undercoat De-Shedding Rake", brand: "FurGone", subGroup: "Grooming & Hygiene", unit: "Piece", currentStock: 18, salePrice: 750, purchasePrice: 390, size: "Dual-Density Teeth (Large)", accType: "Grooming & Hygiene" },
  { itemCode: "A-0023", name: "Professional Pet Nail Clipper with Safety Guard", brand: "PawsTrim", subGroup: "Grooming & Hygiene", unit: "Piece", currentStock: 25, salePrice: 480, purchasePrice: 240, size: "Medium/Large Dogs", accType: "Grooming & Hygiene" },
  { itemCode: "A-0024", name: "Pet Toothbrush Dual-Headed + Enzymatic Paste Set", brand: "DentiPet", subGroup: "Grooming & Hygiene", unit: "Box", currentStock: 28, salePrice: 420, purchasePrice: 210, size: "Brush + 70g Beef Paste", accType: "Grooming & Hygiene" },
  { itemCode: "A-0025", name: "Soft Breathable Mesh Dog Muzzle (Size 4)", brand: "SafeBite", subGroup: "Training & Safety", unit: "Piece", currentStock: 14, salePrice: 380, purchasePrice: 190, size: "Size 4 (Snout 24-28cm)", accType: "Training & Safety" },
  { itemCode: "A-0026", name: "Soft Breathable Mesh Dog Muzzle (Size 2)", brand: "SafeBite", subGroup: "Training & Safety", unit: "Piece", currentStock: 16, salePrice: 340, purchasePrice: 170, size: "Size 2 (Snout 16-20cm)", accType: "Training & Safety" },
  { itemCode: "A-0027", name: "Elizabeth Protective Recovery Collar (Cone) 25cm", brand: "VetCare", subGroup: "Medical & Recovery", unit: "Piece", currentStock: 20, salePrice: 350, purchasePrice: 160, size: "Depth 25cm (Large Breeds)", accType: "Medical & Recovery" },
  { itemCode: "A-0028", name: "Elizabeth Protective Recovery Collar (Cone) 15cm", brand: "VetCare", subGroup: "Medical & Recovery", unit: "Piece", currentStock: 24, salePrice: 260, purchasePrice: 120, size: "Depth 15cm (Cats & Small Dogs)", accType: "Medical & Recovery" },
  { itemCode: "A-0029", name: "Inflatable Soft Pet Recovery E-Collar (L)", brand: "ComfyCare", subGroup: "Medical & Recovery", unit: "Piece", currentStock: 10, salePrice: 850, purchasePrice: 460, size: "Large (Neck 38-50cm)", accType: "Medical & Recovery" },
  { itemCode: "A-0030", name: "Hard-Sided Airline Approved Pet Carrier (M)", brand: "TravelPaws", subGroup: "Carriers & Travel", unit: "Unit", currentStock: 7, salePrice: 2800, purchasePrice: 1650, size: "Medium (58x37x37cm, up to 10kg)", accType: "Carriers & Travel" },
  { itemCode: "A-0031", name: "Foldable Fabric Soft Pet Travel Crate (XL)", brand: "NomadPet", subGroup: "Carriers & Travel", unit: "Unit", currentStock: 5, salePrice: 3600, purchasePrice: 2200, size: "XL (92x64x64cm)", accType: "Carriers & Travel" },
  { itemCode: "A-0032", name: "Pet Seat Belt Tether for Car Travel", brand: "AutoPet", subGroup: "Carriers & Travel", unit: "Piece", currentStock: 30, salePrice: 290, purchasePrice: 130, size: "Universal Adjustable (50-75cm)", accType: "Carriers & Travel" },
  { itemCode: "A-0033", name: "Natural Sisal Cat Scratching Post with Ball (60cm)", brand: "ScratchPro", subGroup: "Toys & Scratchers", unit: "Piece", currentStock: 12, salePrice: 1100, purchasePrice: 620, size: "Height 60cm with Base", accType: "Toys & Scratchers" },
  { itemCode: "A-0034", name: "Durable Natural Rubber Treat-Dispensing Chew Toy (L)", brand: "ChewMax", subGroup: "Toys & Scratchers", unit: "Piece", currentStock: 25, salePrice: 480, purchasePrice: 240, size: "Large (Tough Chewer)", accType: "Toys & Scratchers" },
  { itemCode: "A-0035", name: "Interactive Laser & Feather Feline Wand Toy", brand: "PlayPurr", subGroup: "Toys & Scratchers", unit: "Piece", currentStock: 35, salePrice: 280, purchasePrice: 110, size: "3-in-1 Telescopic Wand", accType: "Toys & Scratchers" },
].map((it): SeedItem => ({
  itemCode: it.itemCode,
  productType: "ACCESSORY",
  name: it.name,
  genericName: `${it.accType} for Companion Animals`,
  brand: it.brand,
  manufacturer: `${it.brand} Equipment Ltd.`,
  description: `${it.name} - Sample catalog price flagged for clinic review before final go-live.`,
  category: "Animal Accessories",
  subGroup: it.subGroup,
  hasVariants: true,
  sku: `ACC-${it.itemCode}`,
  unit: it.unit as any,
  purchaseUom: "Unit",
  salesUom: "Unit",
  uomConversions: [],
  maintainStock: true,
  valuationMethod: "FIFO",
  currentStock: it.currentStock,
  minStockLevel: Math.max(2, Math.floor(it.currentStock * 0.3)),
  reorderLevel: Math.max(4, Math.floor(it.currentStock * 0.5)),
  reorderQty: Math.max(10, it.currentStock),
  safetyStock: 2,
  storageLocation: "Retail Accessories Section",
  batchTracking: false,
  serialTracking: false,
  allowNegativeStock: false,
  defaultSalePrice: it.salePrice,
  defaultPurchasePrice: it.purchasePrice,
  mrp: Math.round(it.salePrice * 1.15),
  minSalePrice: Math.round(it.salePrice * 0.85),
  maxDiscountPct: 10,
  valuationRate: it.purchasePrice,
  lastPurchaseRate: it.purchasePrice,
  gstRate: 18,
  hsnCode: "42010000",
  taxCategory: "Pet Gear Standard",
  isZeroRated: false,
  isExempt: false,
  isImport: false,
  defaultSupplierId: "SUP-05",
  defaultSupplierName: "PetCare Gear India",
  leadTimeDays: 7,
  minOrderQty: 5,
  purchaseAccount: "5020 - Accessories Inventory",
  expenseAccount: "5220 - Cost of Accessories",
  incomeAccount: "4220 - Accessories Sales",
  costCenter: "Retail Floor",
  isSalesItem: true,
  allowAlternativeItem: false,
  status: "Active",
  createdAt: "2025-06-01",
  accessoryDetails: {
    accessoryType: it.accType,
    sizeVariant: it.size,
  },
}));

// Total 52 items
export const ALL_SEED_ITEMS: SeedItem[] = [
  ...SEED_MEDICINES,
  ...SEED_FOOD,
  ...SEED_ACCESSORIES,
];
